-- the cardinality identities a BPMN emission owes, against the relation supplying each expected count.
SELECT * FROM (VALUES
  ('pools',   '|participant| = |filing|',      'epistemics/documents',     'participant',
              'a document rendered as two pools, or two rendered as one'),
  ('lanes',   '|lane| = |layer|',              'layers/every_layer',       'lane',
              'a partition rendered as an overlap: the falsifier, drawn'),
  ('tasks',   '|task| = |operation|',          'entries/operations',       'task',
              'an operation dropped, or a flow node invented to make the picture read'),
  ('calls',   '|callActivity| = |part crossing a document|', 'diagrams/foreign_calls', 'callActivity',
              '⛔ ONE LAW OVER TWO ELEMENTS WOULD LET A LOCAL PART BE RENDERED AS AN ACTIVITY. A local fusion is a PARTITION of the composed layer, not a node inside it. Splitting the law is also what makes the flattening measurable: only these parts go through `calledElement`, so this IS the population exposed to the invented-cycle defect'),
  ('nestings', '|childLaneSet| = |layer with a local part|', 'diagrams/nestings', 'childLaneSet',
              '⭐ THE RECURSION EQUIVALENCE, AND BPMN ALREADY HAD THE ELEMENT. A fusion''s parts partition what they compose, and `Lane/childLaneSet` is a SUB-PARTITION. A nested lane is still keyed `(filing, layer)`, so unlike a call it collapses nothing and can invent nothing'),
  ('categories', '|category| = |filing with an induction|', 'diagrams/categories', 'category',
              'a classification scheme emitted into a document that has nothing to classify, or a document with inductions and no scheme to hang them on'),
  ('category_values', '|categoryValue| = |layer induced into|', 'diagrams/categories', 'categoryValue',
              '⭐ N GETTING A NOTATION. The route that does NOT work is a second `laneSet`, which gives every layer two `lane` elements. BPMN''s other mechanism adds no lane at all: `tFlowElement/categoryValueRef` is `maxOccurs="unbounded"`, so the MEMBER declares the cover and no container grows'),
  ('groups',     '|group| = |categoryValue|',    'diagrams/categories', 'group',
              '⭐⭐ THE GLYPH AGAINST THE FACT, AND THE PAIR IS THE ANSWER TO WHAT A GROUP IS. `group` is to `categoryValueRef` what `lane` is to `flowNodeRef`: the drawn shape of an incidence held elsewhere. A categoryValue with no group is a classification nobody drew; a group with no categoryValue is a dashed box that means nothing'),
  ('induced_into', '|categoryValueRef| = |induction|', 'diagrams/category_members', 'categoryValueRef',
              '⛔ AN INDUCTION DROPPED, WHICH `|lane| = |layer|` CANNOT SEE. One operation here draws from `labour` and induces into `capability`; a lane set holds it in one place, so holding it in the draw alone leaves the second incidence out of every emitted document while the layer count still agrees'),
  ('diagrams', '|BPMNDiagram| = |filing|', 'diagrams/pools', 'BPMNDiagram',
              '⭐⭐⭐ THE SVG''S PROPER PLACE IN THE DOCUMENT. `bpmndi:BPMNDiagram` is in `tDefinitions`''s own sequence, and a document without one leaves the SVG stage to INVENT its coordinates while any tool that opens the file lays it out differently: two pictures of one model with nothing tying them'),
  ('planes', '|BPMNPlane| = |filing|', 'diagrams/pools', 'BPMNPlane',
              'one surface per document, naming the collaboration it is a picture OF. A second plane would be a second picture of one model with no way to say which is meant'),
  ('shapes', '|BPMNShape| = every element that owes a box', 'diagrams/shapes', 'BPMNShape',
              '⛔⛔ THE PRIMITIVES ARE NOT ALL OF IT, AND THE TEMPTING ANSWER IS THAT A `group`, AN `association` AND A `textAnnotation` ARE DERIVED FROM THESE BOXES, so filing a derived coordinate files a value that can disagree with whatever computes it. ⭐ That argument holds and it is about the wrong column: `diagrams/shapes.sqlc` carries no coordinate for ANYTHING, so a row there says which elements owe a box and never where it is, and the derivation belongs in the emitter. An element drawn from geometry the document does not declare is an element every other reader of the file loses, without an error'),
  ('edges', '|BPMNEdge| = |association|', 'diagrams/shapes', 'BPMNEdge',
              '⭐ THE ONE ROUTE IN THE NOTATION, and it needs a different carrier from every box here: `bpmndi:BPMNEdge` with `di:waypoint`s, in a third namespace. Counting it with the shapes would make `|BPMNShape|` a number that matches nothing in the document, which is why `diagrams/shapes.sqlc` declares `di` per row'),
  ('legends', '|textAnnotation| = |note a document owes on its face|', 'diagrams/legends', 'textAnnotation',
              '⭐⭐⭐ A FACT PRESENT AND INVISIBLE, WHICH IS WHAT THIS LAW CATCHES. `documentation` is admitted on any base element and drawn in no rendering, so a scope, a coupling search, a dependence''s meaning and a cover''s meaning can all be in the artifact and on no page. `textAnnotation` is the only element in BPMN that puts words on the canvas, and *documentation is spent instead* is true and about the wrong property'),
  ('attributions', '|relationship type=elimination-between| = |between that resolves|', 'eliminations/resolved', 'relationship',
              '⭐⭐⭐ THE SECOND `pm:ForeignId`, AND THE ELEMENT''S TYPE EARNING ITS KEEP. `association` was refused for F because it has no type and a second use makes two facts indistinguishable; `tRelationship/@type` is REQUIRED, so a second relation costs a different string and the laws filter on it. ⛔ The population is the RESOLVED references and not all of them: a QName needs a prefix and a prefix needs an import, so a `between` naming a document nobody filed cannot be pointed at, and the schema calls that filing ORDINARY'),
  ('descents', '|relationship| = |part crossing a document|', 'diagrams/descents', 'relationship',
              '⭐⭐⭐ THE MAPPING''S WIDEST DEMOTION, PROMOTED. `calledElement` names a PROCESS, so 17 layer-grain edges collapsed to 5 document pairs and the layer survived only inside `@name`. ⛔ THE COUNT IS THE WEAK HALF: 17 relationships joining the wrong 17 pairs passes it, which is why the isomorphism law in examples/diagramming/main.rs reads the ENDPOINTS back and compares the edge SET to F'),
  ('citations', '|citation rendered| = |citation filed|', 'diagrams/citations', 'documentation',
              '⭐ A TABLE DECLARED AS MAPPING AND RENDERED NOWHERE, WHICH NO COUNT OF ELEMENTS CAN SEE. Element KINDS are not one to one: the pools and the lanes spend `documentation` too, so a count of that element is exact while this table''s share of it is zero, and `diagrams/ungoverned.sqlc` is the law that checks ATTRIBUTION instead'),
  ('scopes', '|scope stated| = |filing|', 'diagrams/scopes', 'documentation',
              '⛔⛔⛔ THE `invents` STATE, CAUGHT IN THE EMITTER''S OWN PROSE. A sentence about a filing, hardcoded in the emitter, says one thing about every document where the filings differ, and `diagrams/scopes.sqlc` is what each one claims. That is not something a reader infers: the artifact SAYS it. ⭐ A count is not the law that matters here, the ATTRIBUTION one below it is: this only checks that a scope reached every document, and a wrong scope in every document would pass it'),
  ('dependences', '|association| = |coupling|', 'diagrams/dependences', 'association',
              '⭐⭐⭐ THE MODEL''S OWN FALSIFIER, WHICH NO EMITTED DOCUMENT COULD STATE. `pm:Coupling` exists so the model can be REFUTED IN ITS OWN FORMAT, and the reason that rules out `messageFlow` says nothing about `association`, whose `sourceRef` and `targetRef` are unconstrained QNames. ⛔ The law is worth as much for what it CANNOT check: an association carries no magnitude and no observation, so |association| = |coupling| passes while the evidence and the strength are both gone'),
  ('namespaces', '|targetNamespace| = |notation|', 'composition/notations', 'targetNamespace',
              'a document that does not declare the uri it IS, so nothing can reference it'),
  ('imports', '|import| = |cross-document part reference|', 'diagrams/cross_document', 'import',
              'a reference invented by the emitter, or a document reached without being imported'),
  ('in_a_lane', '|flowNodeRef| = |draw| + |part|', 'diagrams/lane_membership', 'flowNodeRef',
              '⛔ an ORPHAN flow node: emitted, counted, and in no lane, so the incidence that put it there is gone from the rendering while every cardinality law still passes'),
  ('definitions',   '|definitions| = |filing|',   'diagrams/pools', 'definitions',
              'a filing emitted twice, or one skipped, which no leaf count would show'),
  ('collaboration', '|collaboration| = |filing|', 'diagrams/pools', 'collaboration',
              'one filing split across two collaborations, so its pool has no single home'),
  ('process',       '|process| = |filing|',       'diagrams/pools', 'process',
              'one filing split into two processes, which makes its layers two partitions'),
  ('lane_set',      '|laneSet| = |filing|',       'diagrams/pools', 'laneSet',
              '⛔ THE ONE THAT GOVERNS THE ELIMINATION: a SECOND lane set is how D and N would both be rendered, and every layer then has two lane elements with nothing but a matching name to say they are one layer'),
  ('documentation', '|documentation| = |sentence a relation states|', 'diagrams/annotated', 'documentation',
              '⛔ DOCUMENTATION IS NOT A CONTAINER, WHICH IS WHAT SEPARATES THIS ROW FROM THE OTHER FOUR. They frame a document and must appear once; this is an ANNOTATION and may sit on any base element, so one per document fires the moment a lane is annotated, which is a law right about a fact and wrong about a kind. ⛔⛔ AND THE IDENTITY BESIDE IT IS PROSE WHERE THE MODEL SIDE IS A RELATION, so `diagrams/annotated.sqlc` can grow an arm with this count staying exact and the sentence describing it going stale. ⭐ A count is also the wrong instrument here and always was, which is what `states` is for: fifteen documents can carry the right number of sentences and each say something no relation states. examples/diagramming/main.rs reads every one back and asks what states it')
) AS l(slug, law, model_side, element, catches)
