-- Load assets/corpus/*.xml into the relations declared by assets/ddl/schema.ddl.

SET search_path TO pm, public;

BEGIN;

TRUNCATE source, elimination, elimination_search, part, coupling, coupling_search,
         induction, draw, operation, holder, slack, nameplate, layer, regime,
         narrowing, bound_origin, claim, absence, stack_scope, fusion, filing CASCADE;

-- assets/dag/edges.sql, generated by examples/compositions/main.rs; the compose DAG as a relation.
\i assets/dag/edges.sql

\set d `cat assets/corpus/enterprise-contract.xml`
INSERT INTO source VALUES ('enterprise-contract', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/corpus/contrato-empresarial.xml`
INSERT INTO source VALUES ('contrato-empresarial', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/corpus/refutation.xml`
INSERT INTO source VALUES ('refutation', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/corpus/unstated.xml`
INSERT INTO source VALUES ('unstated', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/corpus/merge-us-member.xml`
INSERT INTO source VALUES ('merge-us-member', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/corpus/merge-pt-member.xml`
INSERT INTO source VALUES ('merge-pt-member', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/corpus/merge-group-composition.xml`
INSERT INTO source VALUES ('merge-group-composition', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/corpus/merge-holding-composition.xml`
INSERT INTO source VALUES ('merge-holding-composition', XMLPARSE(DOCUMENT :'d'));

-- The stipulations.
\set d `cat assets/fixtures/every-absence.xml`
INSERT INTO source VALUES ('every-absence', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-unserved-excess.xml`
INSERT INTO source VALUES ('every-unserved-excess', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-elimination.xml`
INSERT INTO source VALUES ('every-elimination', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-local-part.xml`
INSERT INTO source VALUES ('every-local-part', XMLPARSE(DOCUMENT :'d'));

\set d `cat assets/fixtures/every-partial-elimination.xml`
INSERT INTO source VALUES ('every-partial-elimination', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-inverting-elimination.xml`
INSERT INTO source VALUES ('every-inverting-elimination', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-derived-elimination.xml`
INSERT INTO source VALUES ('every-derived-elimination', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-unsized-conversion.xml`
INSERT INTO source VALUES ('every-unsized-conversion', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-unit-cycle.xml`
INSERT INTO source VALUES ('every-unit-cycle', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-nested-conversion.xml`
INSERT INTO source VALUES ('every-nested-conversion', XMLPARSE(DOCUMENT :'d'));
\set d `cat assets/fixtures/every-derived-quantity.xml`
INSERT INTO source VALUES ('every-derived-quantity', XMLPARSE(DOCUMENT :'d'));

-- ---------------------------------------------------------------------------
-- Filings.
-- ---------------------------------------------------------------------------
INSERT INTO filing (name, kind, evidence, evidence_absent,
                    prov_party, prov_entered_by, prov_approved_by,
                    prov_standing_taxonomy, prov_standing_value, prov_standing_absent, prov_note)
SELECT s.name,
       x.root,
       x.attests,
       x.absent::absence_reason,
       x.prov_party, x.prov_entered, x.prov_approved,
       x.prov_st_tax, x.prov_st_val, x.prov_st_absent::absence_reason, x.prov_note
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm,
                            'https://example.invalid/assertion/1.0' AS asrt),
       '/*' PASSING s.body
       COLUMNS root    text PATH 'local-name(.)',
               attests text PATH '//pm:attests',
               absent  text PATH '(//pm:evidence|//asrt:evidence)/pm:absent/pm:reason',
               prov_party     text PATH 'asrt:provenance/pm:party',
               prov_entered   text PATH 'asrt:provenance/pm:enteredBy',
               prov_approved  text PATH 'asrt:provenance/pm:approvedBy',
               prov_st_tax    text PATH 'asrt:provenance/pm:standing/pm:term/pm:taxonomy',
               prov_st_val    text PATH 'asrt:provenance/pm:standing/pm:term/pm:value',
               prov_st_absent text PATH 'asrt:provenance/pm:standing/pm:absent/pm:reason',
               prov_note      text PATH 'asrt:provenance/pm:note') x;

-- pm:Regime, in document order.
INSERT INTO regime
SELECT s.name, x.seq, x.id, x.jurisdiction,
       x.f_taxonomy, x.f_value, x.f_absent::absence_reason,
       x.c_taxonomy, x.c_value, x.c_absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:regime' PASSING s.body
       COLUMNS seq          FOR ORDINALITY,
               id           text PATH 'pm:id',
               jurisdiction text PATH 'pm:jurisdiction',
               f_taxonomy   text PATH 'pm:framework/pm:term/pm:taxonomy',
               f_value      text PATH 'pm:framework/pm:term/pm:value',
               f_absent     text PATH 'pm:framework/pm:absent/pm:reason',
               c_taxonomy   text PATH 'pm:chart/pm:term/pm:taxonomy',
               c_value      text PATH 'pm:chart/pm:term/pm:value',
               c_absent     text PATH 'pm:chart/pm:absent/pm:reason') x;

-- asrt:regime at the root of a composition.
INSERT INTO composition_regime
SELECT s.name, x.seq, x.id, x.jurisdiction,
       x.f_taxonomy, x.f_value, x.f_absent::absence_reason,
       x.c_taxonomy, x.c_value, x.c_absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0'      AS pm,
                            'https://example.invalid/assertion/1.0' AS asrt),
       '/asrt:composition/asrt:regime' PASSING s.body
       COLUMNS seq          FOR ORDINALITY,
               id           text PATH 'pm:id',
               jurisdiction text PATH 'pm:jurisdiction',
               f_taxonomy   text PATH 'pm:framework/pm:term/pm:taxonomy',
               f_value      text PATH 'pm:framework/pm:term/pm:value',
               f_absent     text PATH 'pm:framework/pm:absent/pm:reason',
               c_taxonomy   text PATH 'pm:chart/pm:term/pm:taxonomy',
               c_value      text PATH 'pm:chart/pm:term/pm:value',
               c_absent     text PATH 'pm:chart/pm:absent/pm:reason') x;

-- pm:processModulus/pm:notation: the filing, about itself.
INSERT INTO filing_identity
SELECT s.name, x.uri, 'the filing, about itself', x.absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:processModulus/pm:notation' PASSING s.body
       COLUMNS uri    text PATH 'pm:uri',
               absent text PATH 'pm:absent/pm:reason') x;

-- How much of the system each stack holds.
INSERT INTO stack_scope
SELECT s.name, x.extent, x.basis, x.absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:scope' PASSING s.body
       COLUMNS extent text PATH 'pm:scope/pm:extent',
               basis  text PATH 'pm:scope/pm:basis',
               absent text PATH 'pm:absent/pm:reason') x
WHERE s.name IN (SELECT name FROM filing);

-- ---------------------------------------------------------------------------
-- Layers.
-- ---------------------------------------------------------------------------
INSERT INTO layer
SELECT s.name, x.name,
       x.d_low, x.d_mode, x.d_high, x.d_unit, x.d_absent::absence_reason, x.d_derivation::identity,
       x.p_low, x.p_mode, x.p_high, x.p_unit, x.p_absent::absence_reason,
       x.r_absent::absence_reason, x.r_note,
       x.sign::fit, x.sign_absent::absence_reason, x.sign_derivation::identity,
       x.absorber_taxonomy, x.absorber_value, x.absorber_absent::absence_reason,
       x.q_low, x.q_mode, x.q_high, x.q_unit, x.q_absent::absence_reason, x.q_derivation::identity
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:layer' PASSING s.body
       COLUMNS
         name     text    PATH 'pm:name',
         d_low    numeric PATH 'pm:demand/pm:amount/pm:claim/pm:low',
         d_mode   numeric PATH 'pm:demand/pm:amount/pm:claim/pm:mostLikely',
         d_high   numeric PATH 'pm:demand/pm:amount/pm:claim/pm:high',
         d_unit   text    PATH 'pm:demand/pm:amount/pm:claim/pm:unit',
         d_absent text    PATH 'pm:demand/pm:amount/pm:absent/pm:reason',
         d_derivation text PATH 'pm:demand/pm:amount/pm:derivation/pm:identity',
         p_low    numeric PATH 'pm:demand/pm:patience/pm:claim/pm:low',
         p_mode   numeric PATH 'pm:demand/pm:patience/pm:claim/pm:mostLikely',
         p_high   numeric PATH 'pm:demand/pm:patience/pm:claim/pm:high',
         p_unit   text    PATH 'pm:demand/pm:patience/pm:claim/pm:unit',
         p_absent text    PATH 'pm:demand/pm:patience/pm:absent/pm:reason',
         r_absent text PATH 'pm:remainder/pm:absent/pm:reason',
         r_note   text PATH 'pm:remainder/pm:absent/pm:note',
         sign        text PATH 'pm:remainder/pm:remainder/pm:sign/pm:fit',
         sign_absent text PATH 'pm:remainder/pm:remainder/pm:sign/pm:absent/pm:reason',
         sign_derivation text PATH 'pm:remainder/pm:remainder/pm:sign/pm:derivation/pm:identity',
         absorber_taxonomy text PATH 'pm:remainder/pm:remainder/pm:absorber/pm:term/pm:taxonomy',
         absorber_value    text PATH 'pm:remainder/pm:remainder/pm:absorber/pm:term/pm:value',
         absorber_absent   text PATH 'pm:remainder/pm:remainder/pm:absorber/pm:absent/pm:reason',
         q_low    numeric PATH 'pm:remainder/pm:remainder/pm:quantity/pm:claim/pm:low',
         q_mode   numeric PATH 'pm:remainder/pm:remainder/pm:quantity/pm:claim/pm:mostLikely',
         q_high   numeric PATH 'pm:remainder/pm:remainder/pm:quantity/pm:claim/pm:high',
         q_unit   text    PATH 'pm:remainder/pm:remainder/pm:quantity/pm:claim/pm:unit',
         q_absent text    PATH 'pm:remainder/pm:remainder/pm:quantity/pm:absent/pm:reason',
         q_derivation text PATH 'pm:remainder/pm:remainder/pm:quantity/pm:derivation/pm:identity') x;

-- ---------------------------------------------------------------------------
-- Nameplates. Wide: these are attributes of one supply, not matrix entries.
-- ---------------------------------------------------------------------------
INSERT INTO nameplate
SELECT s.name, x.layer, x.label,
       x.a_low, x.a_mode, x.a_high, x.a_unit, x.a_absent::absence_reason, x.a_derivation::identity,
       x.a_origin::constraint_origin, x.a_origin_absent::absence_reason,
       CASE WHEN x.n_divisibility = 0 THEN NULL ELSE x.n_continuous = 0 END,
       x.div_absent::absence_reason,
       x.k_low, x.k_mode, x.k_high, x.k_unit, x.k_absent::absence_reason, x.k_origin::constraint_origin,
       x.w_low, x.w_mode, x.w_high, x.w_unit, x.w_size_absent::absence_reason,
       x.w_origin::constraint_origin,
       x.w_absent::absence_reason,
       x.dr_low, x.dr_mode, x.dr_high, x.dr_unit, x.dr_absent::absence_reason,
       x.dr_derivation::identity,
       x.mb_contributed, x.mb_taxonomy, x.mb_value, x.mb_absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:layer' PASSING s.body
       COLUMNS
         layer    text PATH 'pm:name',
         label    text PATH 'pm:supply/pm:label',
         a_low    numeric PATH 'pm:supply/pm:nameplate/pm:amount/pm:claim/pm:low',
         a_mode   numeric PATH 'pm:supply/pm:nameplate/pm:amount/pm:claim/pm:mostLikely',
         a_high   numeric PATH 'pm:supply/pm:nameplate/pm:amount/pm:claim/pm:high',
         a_unit   text    PATH 'pm:supply/pm:nameplate/pm:amount/pm:claim/pm:unit',
         a_absent text    PATH 'pm:supply/pm:nameplate/pm:amount/pm:absent/pm:reason',
         a_derivation text PATH 'pm:supply/pm:nameplate/pm:amount/pm:derivation/pm:identity',
         a_origin text    PATH 'pm:supply/pm:nameplate/pm:amountOrigin/pm:origin',
         a_origin_absent text PATH 'pm:supply/pm:nameplate/pm:amountOrigin/pm:absent/pm:reason',
         n_nameplate  numeric PATH 'count(pm:supply/pm:nameplate)',
         n_continuous numeric PATH 'count(pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:continuous)',
         n_divisibility numeric PATH 'count(pm:supply/pm:nameplate/pm:divisibility/pm:divisibility)',
         div_absent text PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:absent/pm:reason',
         k_low    numeric PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:lumpy/pm:size/pm:claim/pm:low',
         k_mode   numeric PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:lumpy/pm:size/pm:claim/pm:mostLikely',
         k_high   numeric PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:lumpy/pm:size/pm:claim/pm:high',
         k_unit   text    PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:lumpy/pm:size/pm:claim/pm:unit',
         k_absent text    PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:lumpy/pm:size/pm:absent/pm:reason',
         k_origin text    PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:lumpy/pm:origin',
         w_low    numeric PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:window/pm:quantum/pm:size/pm:claim/pm:low',
         w_mode   numeric PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:window/pm:quantum/pm:size/pm:claim/pm:mostLikely',
         w_high   numeric PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:window/pm:quantum/pm:size/pm:claim/pm:high',
         w_unit   text    PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:window/pm:quantum/pm:size/pm:claim/pm:unit',
         w_size_absent text PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:window/pm:quantum/pm:size/pm:absent/pm:reason',
         w_origin text    PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:window/pm:quantum/pm:origin',
         w_absent text    PATH 'pm:supply/pm:nameplate/pm:divisibility/pm:divisibility/pm:window/pm:absent/pm:reason',
         dr_low   numeric PATH 'pm:supply/pm:jagged/pm:draw/pm:claim/pm:low',
         dr_mode  numeric PATH 'pm:supply/pm:jagged/pm:draw/pm:claim/pm:mostLikely',
         dr_high  numeric PATH 'pm:supply/pm:jagged/pm:draw/pm:claim/pm:high',
         dr_unit  text    PATH 'pm:supply/pm:jagged/pm:draw/pm:claim/pm:unit',
         dr_absent text   PATH 'pm:supply/pm:jagged/pm:draw/pm:absent/pm:reason',
         dr_derivation text PATH 'pm:supply/pm:jagged/pm:draw/pm:derivation/pm:identity',
         mb_contributed text PATH 'pm:supply/pm:jagged/pm:measurementBasis/pm:basis/pm:contributed',
         mb_taxonomy text PATH 'pm:supply/pm:jagged/pm:measurementBasis/pm:basis/pm:borrowed/pm:taxonomy',
         mb_value    text PATH 'pm:supply/pm:jagged/pm:measurementBasis/pm:basis/pm:borrowed/pm:value',
         mb_absent   text PATH 'pm:supply/pm:jagged/pm:measurementBasis/pm:absent/pm:reason') x
WHERE x.layer IN (SELECT layer FROM layer WHERE filing = s.name)
  AND x.n_nameplate > 0;   -- `Facility` requires a nameplate; this keeps an invalid document from filing a row of NULLs

-- ---------------------------------------------------------------------------
-- S, tall. Three inserts, one per buffer, and the union is the L x 3 matrix.
-- ---------------------------------------------------------------------------
INSERT INTO slack
SELECT s.name, x.layer, 'time'::buffer, x.low, x.mode, x.high, x.unit,
       x.absent::absence_reason, x.derivation::identity
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:layer' PASSING s.body
       COLUMNS layer text PATH 'pm:name',
               low   numeric PATH 'pm:timeSlack/pm:claim/pm:low',
               mode  numeric PATH 'pm:timeSlack/pm:claim/pm:mostLikely',
               high  numeric PATH 'pm:timeSlack/pm:claim/pm:high',
               unit  text    PATH 'pm:timeSlack/pm:claim/pm:unit',
               absent text   PATH 'pm:timeSlack/pm:absent/pm:reason',
               derivation text PATH 'pm:timeSlack/pm:derivation/pm:identity') x
WHERE x.layer IN (SELECT layer FROM layer WHERE filing = s.name);

INSERT INTO slack
SELECT s.name, x.layer, x.buf::buffer, x.low, x.mode, x.high, x.unit,
       x.absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:layer' PASSING s.body
       COLUMNS layer text PATH 'pm:name',
               buf   text PATH '''capacity''',
               low   numeric PATH 'pm:supply/pm:nameplate/pm:capacitySlack/pm:claim/pm:low',
               mode  numeric PATH 'pm:supply/pm:nameplate/pm:capacitySlack/pm:claim/pm:mostLikely',
               high  numeric PATH 'pm:supply/pm:nameplate/pm:capacitySlack/pm:claim/pm:high',
               unit  text    PATH 'pm:supply/pm:nameplate/pm:capacitySlack/pm:claim/pm:unit',
               absent text   PATH 'pm:supply/pm:nameplate/pm:capacitySlack/pm:absent/pm:reason') x
WHERE x.layer IN (SELECT layer FROM layer WHERE filing = s.name);

INSERT INTO slack
SELECT s.name, x.layer, 'inventory'::buffer, x.low, x.mode, x.high, x.unit,
       x.absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:layer' PASSING s.body
       COLUMNS layer text PATH 'pm:name',
               low   numeric PATH 'pm:supply/pm:nameplate/pm:inventorySlack/pm:claim/pm:low',
               mode  numeric PATH 'pm:supply/pm:nameplate/pm:inventorySlack/pm:claim/pm:mostLikely',
               high  numeric PATH 'pm:supply/pm:nameplate/pm:inventorySlack/pm:claim/pm:high',
               unit  text    PATH 'pm:supply/pm:nameplate/pm:inventorySlack/pm:claim/pm:unit',
               absent text   PATH 'pm:supply/pm:nameplate/pm:inventorySlack/pm:absent/pm:reason') x
WHERE x.layer IN (SELECT layer FROM layer WHERE filing = s.name);

-- ---------------------------------------------------------------------------
-- H, tall. A row per bearer.
-- ---------------------------------------------------------------------------
INSERT INTO holder
SELECT s.name, x.layer, x.kind::holder_kind,
       x.low, x.mode, x.high, x.unit, x.absent::absence_reason, x.derivation::identity,
       x.party, x.as_of::date
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:layer/pm:remainder/pm:remainder/pm:holder/pm:holder' PASSING s.body
       COLUMNS layer text PATH '../../../../pm:name',
               kind  text PATH 'pm:kind',
               low   numeric PATH 'pm:share/pm:claim/pm:low',
               mode  numeric PATH 'pm:share/pm:claim/pm:mostLikely',
               high  numeric PATH 'pm:share/pm:claim/pm:high',
               unit  text    PATH 'pm:share/pm:claim/pm:unit',
               absent text   PATH 'pm:share/pm:absent/pm:reason',
               derivation text PATH 'pm:share/pm:derivation/pm:identity',
               party text    PATH 'pm:party',
               as_of text    PATH 'pm:asOf') x;

-- pm:Claim, wherever one appears, across two schemas.
INSERT INTO claim
SELECT s.name, x.seq, x.owns, x.layer, x.low, x.mode, x.high, x.unit,
       coalesce(x.period, x.each),
       CASE WHEN x.period IS NOT NULL THEN 'period'
            WHEN x.each   IS NOT NULL THEN 'each' END,
       x.absent::absence_reason,
       x.prov_party, x.prov_entered, x.prov_approved,
       x.prov_st_tax, x.prov_st_val, x.prov_st_absent::absence_reason, x.prov_note,
       x.as_of::date
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:claim' PASSING s.body
       COLUMNS seq FOR ORDINALITY,
               owns text    PATH 'concat(name(../..),"/",name(..))',
               layer text   PATH 'ancestor::pm:layer/pm:name',
               low  numeric PATH 'pm:low',
               mode numeric PATH 'pm:mostLikely',
               high numeric PATH 'pm:high',
               unit text    PATH 'pm:unit',
               period text  PATH 'pm:denominator/pm:period',
               each   text  PATH 'pm:denominator/pm:each',
               absent text  PATH 'pm:denominator/pm:absent/pm:reason',
               prov_party   text PATH 'pm:provenance/pm:party',
               prov_entered text PATH 'pm:provenance/pm:enteredBy',
               prov_approved text PATH 'pm:provenance/pm:approvedBy',
               prov_st_tax  text PATH 'pm:provenance/pm:standing/pm:term/pm:taxonomy',
               prov_st_val  text PATH 'pm:provenance/pm:standing/pm:term/pm:value',
               prov_st_absent text PATH 'pm:provenance/pm:standing/pm:absent/pm:reason',
               prov_note    text PATH 'pm:provenance/pm:note',
               as_of        text PATH 'pm:asOf') x;

-- Every narrowing anywhere in the document, in document order.
INSERT INTO narrowing
SELECT s.name, x.seq, x.condition, x.kind::narrowing_kind, x.absent::absence_reason,
       x.derivation::identity
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:narrowsWhen' PASSING s.body
       COLUMNS seq FOR ORDINALITY,
               condition text PATH 'pm:narrowing/pm:condition',
               kind      text PATH 'pm:narrowing/pm:kind',
               absent    text PATH 'pm:absent/pm:reason',
               derivation text PATH 'pm:derivation/pm:identity') x;

-- pm:Claim/pm:boundOrigin, in the same document order as the claims above.
INSERT INTO bound_origin
SELECT s.name, x.seq, x.origin::constraint_origin, x.absent::absence_reason,
       x.derivation::identity
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:boundOrigin' PASSING s.body
       COLUMNS seq FOR ORDINALITY,
               origin text PATH 'pm:origin',
               absent text PATH 'pm:absent/pm:reason',
               derivation text PATH 'pm:derivation/pm:identity') x;

-- pm:Absence and pm:ClaimAbsence, every one, in document order.
INSERT INTO absence
SELECT s.name, x.seq, x.owns, x.layer, x.reason::absence_reason, x.note, x.as_of::date,
       x.prov_party, x.prov_entered, x.prov_approved,
       x.prov_st_tax, x.prov_st_val, x.prov_st_absent::absence_reason, x.prov_note
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm,
                            'https://example.invalid/assertion/1.0' AS asrt),
       '//pm:absent | //asrt:absent' PASSING s.body
       COLUMNS seq FOR ORDINALITY,
               owns   text PATH 'concat(name(../..),"/",name(..))',
               layer  text PATH 'ancestor::pm:layer/pm:name',
               reason text PATH 'pm:reason',
               note   text PATH 'pm:note',
               as_of  text PATH 'pm:asOf',
               prov_party     text PATH 'pm:provenance/pm:party',
               prov_entered   text PATH 'pm:provenance/pm:enteredBy',
               prov_approved  text PATH 'pm:provenance/pm:approvedBy',
               prov_st_tax    text PATH 'pm:provenance/pm:standing/pm:term/pm:taxonomy',
               prov_st_val    text PATH 'pm:provenance/pm:standing/pm:term/pm:value',
               prov_st_absent text PATH 'pm:provenance/pm:standing/pm:absent/pm:reason',
               prov_note      text PATH 'pm:provenance/pm:note') x;

-- pm:Derivation and its restrictions, every one, in document order.
INSERT INTO derivation
SELECT s.name, x.seq, x.owns, NULLIF(x.claim_owns, '/'), x.layer, x.identity::identity, x.note,
       x.as_of::date,
       x.prov_party, x.prov_entered, x.prov_approved,
       x.prov_st_tax, x.prov_st_val, x.prov_st_absent::absence_reason, x.prov_note
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm,
                            'https://example.invalid/assertion/1.0' AS asrt),
       '//pm:derivation' PASSING s.body
       COLUMNS seq FOR ORDINALITY,
               owns     text PATH 'concat(name(../..),"/",name(..))',
               claim_owns text PATH 'concat(name(../parent::pm:claim/../..),"/",name(../parent::pm:claim/..))',
               layer    text PATH 'ancestor::pm:layer/pm:name',
               identity text PATH 'pm:identity',
               note     text PATH 'pm:note',
               as_of    text PATH 'pm:asOf',
               prov_party     text PATH 'pm:provenance/pm:party',
               prov_entered   text PATH 'pm:provenance/pm:enteredBy',
               prov_approved  text PATH 'pm:provenance/pm:approvedBy',
               prov_st_tax    text PATH 'pm:provenance/pm:standing/pm:term/pm:taxonomy',
               prov_st_val    text PATH 'pm:provenance/pm:standing/pm:term/pm:value',
               prov_st_absent text PATH 'pm:provenance/pm:standing/pm:absent/pm:reason',
               prov_note      text PATH 'pm:provenance/pm:note') x;

-- ---------------------------------------------------------------------------
-- Operations, and the two matrices that hang off them.
-- ---------------------------------------------------------------------------
-- pm:Operation: the label, and the position in a process notation where the filer named one.
INSERT INTO operation
SELECT s.name, x.label, x.notation, x.foreign_id, x.absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:operation' PASSING s.body
       COLUMNS label      text PATH 'pm:label',
               notation   text PATH 'pm:notationPosition/pm:foreignId/pm:notation',
               foreign_id text PATH 'pm:notationPosition/pm:foreignId/pm:id',
               absent     text PATH 'pm:notationPosition/pm:absent/pm:reason') x;

-- D, tall. What an operation takes from a layer, now.
INSERT INTO draw
SELECT s.name, x.op, x.layer, x.low, x.mode, x.high, x.unit, x.absent::absence_reason
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:operation/pm:draw' PASSING s.body
       COLUMNS op    text PATH '../pm:label',
               layer text PATH 'pm:layer',
               low   numeric PATH 'pm:quantity/pm:claim/pm:low',
               mode  numeric PATH 'pm:quantity/pm:claim/pm:mostLikely',
               high  numeric PATH 'pm:quantity/pm:claim/pm:high',
               unit  text    PATH 'pm:quantity/pm:claim/pm:unit',
               absent text   PATH 'pm:quantity/pm:absent/pm:reason') x;

-- N, tall.
INSERT INTO induction
SELECT s.name, x.op, x.layer, x.low, x.mode, x.high, x.unit, x.absent::absence_reason, x.decider
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:operation/pm:induces' PASSING s.body
       COLUMNS op    text PATH '../pm:label',
               layer text PATH 'pm:layer',
               low   numeric PATH 'pm:commitment/pm:claim/pm:low',
               mode  numeric PATH 'pm:commitment/pm:claim/pm:mostLikely',
               high  numeric PATH 'pm:commitment/pm:claim/pm:high',
               unit  text    PATH 'pm:commitment/pm:claim/pm:unit',
               absent text   PATH 'pm:commitment/pm:absent/pm:reason',
               decider text  PATH 'pm:decidedBy') x;

-- C, tall.
INSERT INTO coupling
SELECT s.name, x.f, x.t, x.low, x.mode, x.high, x.unit,
       x.s_absent::absence_reason, x.observed
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:couplings/pm:coupling' PASSING s.body
       COLUMNS f text PATH 'pm:from',
               t text PATH 'pm:to',
               low  numeric PATH 'pm:strength/pm:claim/pm:low',
               mode numeric PATH 'pm:strength/pm:claim/pm:mostLikely',
               high numeric PATH 'pm:strength/pm:claim/pm:high',
               unit text    PATH 'pm:strength/pm:claim/pm:unit',
               s_absent text PATH 'pm:strength/pm:absent/pm:reason',
               observed text PATH 'pm:observed') x;

-- pm:Stack/pm:couplings, the search beside C.
INSERT INTO coupling_search
SELECT s.name, x.absent::absence_reason, x.note
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/process-flow/1.0' AS pm),
       '//pm:stack/pm:couplings' PASSING s.body
       COLUMNS absent text PATH 'pm:absent/pm:reason',
               note   text PATH 'pm:absent/pm:note') x
WHERE s.name IN (SELECT name FROM filing);

-- asrt:Fusion: the composed layer it names and what the composer observed.
INSERT INTO fusion
SELECT s.name, f.composed, f.observed
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt),
       '//asrt:fusion' PASSING s.body
       COLUMNS composed text PATH 'asrt:name',
               observed text PATH 'asrt:observed') f;

-- ---------------------------------------------------------------------------
-- F and Phi in one table.
-- ---------------------------------------------------------------------------
INSERT INTO part
SELECT s.name, f.composed, p.pf, p.pl, p.p_regime, p.f_low, p.f_mode, p.f_high,
       p.f_absent::absence_reason, p.f_derivation::identity,
       p.party, p.reg_taxonomy, p.reg_value, p.version
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt),
       '//asrt:fusion' PASSING s.body
       COLUMNS composed text PATH 'asrt:name', frag xml PATH '.') f,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt,
                            'https://example.invalid/process-flow/1.0' AS pm),
       '/asrt:fusion/asrt:part' PASSING f.frag
       COLUMNS pf text PATH 'asrt:layer/asrt:filing/pm:notation',
               pl text PATH 'asrt:layer/asrt:filing/pm:id',
               p_regime text PATH 'asrt:layer/asrt:regime',
               f_low  numeric PATH 'asrt:factor/pm:claim/pm:low',
               f_mode numeric PATH 'asrt:factor/pm:claim/pm:mostLikely',
               f_high numeric PATH 'asrt:factor/pm:claim/pm:high',
               f_absent text PATH 'asrt:factor/pm:absent/pm:reason',
               f_derivation text PATH 'asrt:factor/pm:derivation/pm:identity',
               party    text PATH 'asrt:layer/asrt:party',
               reg_taxonomy text PATH 'asrt:layer/asrt:registration/pm:taxonomy',
               reg_value    text PATH 'asrt:layer/asrt:registration/pm:value',
               version  text PATH 'asrt:layer/asrt:version') p;

-- e_x. One row per quantity eliminated.
INSERT INTO elimination
SELECT s.name, e.composed, e.against::summed_quantity, e.low, e.mode, e.high, e.unit,
       e.absent::absence_reason, e.derivation::identity, e.observed,
       CASE WHEN e.low IS NOT NULL THEN e.claim_seq END
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt,
                            'https://example.invalid/process-flow/1.0' AS pm),
       '//asrt:fusion/asrt:eliminations/asrt:elimination' PASSING s.body
       COLUMNS composed text PATH 'ancestor::asrt:fusion/asrt:name',
               against text PATH 'asrt:against',
               low  numeric PATH 'asrt:quantity/pm:claim/pm:low',
               mode numeric PATH 'asrt:quantity/pm:claim/pm:mostLikely',
               high numeric PATH 'asrt:quantity/pm:claim/pm:high',
               unit text    PATH 'asrt:quantity/pm:claim/pm:unit',
               absent text  PATH 'asrt:quantity/pm:absent/pm:reason',
               derivation text PATH 'asrt:quantity/pm:derivation/pm:identity',
               observed text PATH 'asrt:observed',
               claim_seq int PATH 'count(asrt:quantity/pm:claim/preceding::pm:claim) + 1') e;

-- asrt:Fusion/asrt:eliminations/pm:absent, the search beside e.
INSERT INTO elimination_search
SELECT s.name, f.composed, e.absent::absence_reason, e.note
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt),
       '//asrt:fusion' PASSING s.body
       COLUMNS composed text PATH 'asrt:name', frag xml PATH '.') f,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt,
                            'https://example.invalid/process-flow/1.0' AS pm),
       '/asrt:fusion/asrt:eliminations' PASSING f.frag
       COLUMNS absent text PATH 'asrt:absent/pm:reason',
               note   text PATH 'asrt:absent/pm:note') e;

-- asrt:Elimination/between.
INSERT INTO elimination_between
SELECT s.name, f.composed, e.against::summed_quantity, b.seq, b.party, b.notation, b.layer, b.version, b.regime,
       b.reg_taxonomy, b.reg_value
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt),
       '//asrt:fusion' PASSING s.body
       COLUMNS composed text PATH 'asrt:name', frag xml PATH '.') f,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt),
       '/asrt:fusion/asrt:eliminations/asrt:elimination' PASSING f.frag
       COLUMNS against text PATH 'asrt:against', efrag xml PATH '.') e,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt,
                            'https://example.invalid/process-flow/1.0' AS pm),
       '/asrt:elimination/asrt:between' PASSING e.efrag
       COLUMNS seq      FOR ORDINALITY,
               party    text PATH 'asrt:party',
               notation text PATH 'asrt:filing/pm:notation',
               layer    text PATH 'asrt:filing/pm:id',
               version  text PATH 'asrt:version',
               regime   text PATH 'asrt:regime',
               reg_taxonomy text PATH 'asrt:registration/pm:taxonomy',
               reg_value    text PATH 'asrt:registration/pm:value') b;

-- asrt:Composition/citation.
INSERT INTO composition_citation
SELECT s.name, c.seq, c.taxonomy, c.instrument, c.clause, c.version
FROM source s,
     XMLTABLE(XMLNAMESPACES('https://example.invalid/assertion/1.0' AS asrt,
                            'https://example.invalid/process-flow/1.0' AS pm),
       '//asrt:composition/asrt:citation' PASSING s.body
       COLUMNS seq        FOR ORDINALITY,
               taxonomy   text PATH 'asrt:instrument/pm:taxonomy',
               instrument text PATH 'asrt:instrument/pm:value',
               clause     text PATH 'asrt:clause',
               version    text PATH 'asrt:version') c;

SET CONSTRAINTS ALL IMMEDIATE;

COMMIT;

-- every table the load just filled.
ANALYZE;
