-- algebra/roster.sqlc against public.compose_edge: who composes the layer dimension.
SELECT a.law, p.subject, p.holds, p.detail
FROM      (
    -- the set-algebraic laws this tree's relations claim to obey.
SELECT * FROM (VALUES
  ('decomposition',    '|E| = Σ_filing |E_filing|',  'rank/decomposition',               'partition',  'bag: one edge counted in both scopes'),
  -- ⭐⭐⭐ NOT A SET IDENTITY, AND IT IS THE FIRST ROW HERE THAT IS NOT. Every other law on this
  --    roster is a cardinality identity over relations. This one is about the compose DAG: which
  --    templates may compose the layer DIMENSION. A dimension reaches every layer by
  --    construction, so a relation composing it hands the whole dimension to every consumer, and
  --    any downstream bound of the form *this reach is inside that reach* goes vacuous. Measured:
  --    one edge put the dimension into 20 of 29 rules' closures.
  ('dimension_use',    'parents(dimension) ⊆ declared', 'algebra/dimension_use',         'roster',     'set: one row per undeclared parent'),
  ('owed_equality',    '|A| = |A∖B| + |A⋉B|',        'composition/owed_equality',        'difference', 'set'),
  ('leaves',           '|A| = |A∖B| + |A⋉B|',        'composition/leaves',               'difference', 'bag: dedup would be a defect'),
  ('jagged_layers',    '|A| = |A∖B| + |A⋉B|',        'queries/observations/14-jagged-layers','difference','bag: one row per doubled layer'),
  ('composed_demand',  '|A| = |A∖B| + |A⋉B|',        'queries/matrices/3b-composed-demand','difference','set'),
  ('integrity',        '|A| = |A∖B| + |A⋉B|',        'reports/integrity',                'difference', 'bag: dedup intended'),
  ('carried',          '|A| = |A∖B| + |A⋉B|',        'composition/carried',              'difference', 'bag: anti-join preserves it'),
  ('owed_remainder',   '|A| = |A∖B| + |A⋉B|',        'composition/owed_remainder',       'difference', 'set'),
  ('settled_remainders','|A| = |A∖B| + |A⋉B|',       'composition/settled_remainders',   'difference', 'bag: one row per path'),
  ('borne',            'Σall = Σkept + Σremoved',    'entries/borne',                    'additive',   'bag: γ over holders'),
  ('arithmetic_class', 'each candidate in exactly one class', 'arithmetic/all',          'partition',  'set'),
  ('remainder_standing','each remainder in exactly one standing','layers/remainder_scope','partition',  'set'),
  ('exposure_standing', 'each exposed layer in exactly one standing','layers/exposure_scope','partition','set'),
  ('searches',         '|A ⊎ B| = |A| + |B|',        'epistemics/searches',              'union',      'bag: UNION ALL'),
  ('part_regimes',     '|A| = |A∖B| + |A⋉B|',        'checks/part_regime_disagrees',     'difference', 'set: pm.part''s key')
) AS a(slug, law, governs, form, multiplicity)

) a
LEFT JOIN (
    SELECT 'layers/every_layer.sqlc' AS subject,
           count(*) = 0              AS holds,
           format('%s undeclared parent(s) compose the layer dimension: %s',
                  count(*), coalesce(string_agg(u.parent, ', ' ORDER BY u.parent), '(none)'))
                                     AS detail
    FROM (
        SELECT e.parent
        FROM ( -- public.compose_edge, generated by examples/compositions/main.rs from assets/sqlc/.
SELECT e.parent, e.child, e.splices, e.inner_joins
FROM public.compose_edge e
 ) e
        WHERE e.child = 'layers/every_layer.sqlc'
          AND e.inner_joins > 0
          -- ⭐⭐⭐ ONE ROW, BECAUSE `inner_joins` CARRIES THE SYNTAX. Permitting parents by NAME
          --    would mean adding every ordinary denominator use by hand, and a list like that
          --    rots on changes that are fine. Driving from the dimension or left-joining it
          --    passes without being declared; only an INNER join needs an argument. ⛔ This is
          --    the one that has one: it
          --    self-joins the dimension with `filing <> filing` to find one layer NAME in two
          --    filings, so the whole dimension genuinely is its subject rather than a lookup.
          AND e.parent NOT IN ('entries/spillovers.sqlc')
    ) u
) p ON true
WHERE a.slug = 'dimension_use'
