//! A reading written out as `pm:processModulus`.
//!
//! The filing is written from a reading, never from the history. The instrument decides what is
//! knowable, and this module only writes down what the instrument returned. So two filings come
//! out of one run, and the rules in `assets/sql/checks/` say whether an honest report of what is
//! not known contradicts anything.
//!
//! What the shares have to add up to is exact. `shares_do_not_sum` compares them with the
//! remainder's magnitude at the most likely value, with a tolerance of `1e-9`, so shares that are
//! nearly right are a violation. Counted straight off the history they are nearly right, for two
//! reasons, and both are real:
//!
//! - `pending`: demand that had arrived and was still waiting when the window closed. It is
//!   neither served nor unserved, and no `pm:HolderKind` fits it, because nobody has borne
//!   anything yet.
//! - `undelivered`: rating that never became something a customer could take. On a short layer
//!   this is the residue: supply too small to meet any whole ask.
//!
//! So the shares are filed to add up to the exact magnitude, with the reconciliation written into
//! the filing as a note, so a reader can check the arithmetic.

use super::instrument::{Bounded, Instrument, Reading};
use super::layer::Settings;
use super::window::Run;

/// The unit every claim in a generated filing is quoted in.
///
/// A rate, because of the denominator. `Claim/denominator` gives `Divisibility/window` a period
/// to be a part of, and a nameplate quoted as a bare count has no period to run on.
const UNIT: &str = "units per shift";
const PERIOD: &str = "shift";

/// Which buffers the Factory Physics term comes from.
const BUFFERS: &str = "urn:example:factory-physics:buffers";

pub struct Emitted {
    pub notation: String,
    pub xml: String,
}

/// Writes one run, as one instrument read it, into one filing.
///
/// `case` is part of the notation, and has to be. `filing_identity` holds each notation once, so
/// two runs of the same bench at the same seed under different settings would collide on ingest.
pub fn emit(run: &Run, reading: &Reading, instrument: Instrument, case: &str, as_of: &str) -> Emitted {
    let kind = match instrument {
        Instrument::Whole => "whole",
        Instrument::StockAndFlow => "stock-and-flow",
    };
    let notation = format!(
        "urn:example:filing:bench:{case}:{kind}:seed-{seed}",
        seed = run.seed
    );

    let mut x = String::new();
    x.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    x.push_str(&format!(
        "<!--\n  Generated by examples/shared/simulation, from a NeXosim bench. Do not edit.\n\
n  Instrument: {kind}. {}\n-->\n",
        match instrument {
            Instrument::Whole =>
                "Every field of every event was available, so what is absent here is absent \
                 because the model has no branch for it.",
            Instrument::StockAndFlow =>
                "Only what a stock-and-flow event log records was available: successes with \
                 their totals, failures with a reason and no magnitude, and no event at all \
                 for a demand that gave up waiting.",
        }
    ));
    x.push_str("<pm:processModulus xmlns:pm=\"https://example.invalid/process-flow/1.0\">\n\n");

    x.push_str(&format!(
        "  <pm:notation>\n    <pm:uri>{notation}</pm:uri>\n  </pm:notation>\n"
    ));
    // An observation, not a stipulation. Nobody asserted these figures; a bench ran and they were
    // counted off it. That the bench is itself a model is a fact about the subject, not about how
    // the numbers were obtained.
    x.push_str("  <pm:evidence>\n    <pm:attests>observation</pm:attests>\n  </pm:evidence>\n\n");

    x.push_str("  <pm:stack>\n");
    x.push_str(&format!(
        "    <pm:scope>\n      <pm:scope>\n        <pm:extent>scoped</pm:extent>\n        \
<pm:basis>one line over one shift of {hours} hours, generated by \
         examples/shared/simulation at seed {seed}</pm:basis>\n      </pm:scope>\n    </pm:scope>\n",
        hours = run.window.as_secs() / 3600,
        seed = run.seed
    ));

    x.push_str(&layer(run, reading, instrument, as_of));

    // One layer has nothing to couple to. `notApplicable` rather than `none`, because `none` would
    // say somebody looked for a dependence between two layers, and there is only one.
    x.push_str(
        "    <pm:couplings>\n      <pm:absent>\n        <pm:reason>notApplicable</pm:reason>\n        \
<pm:note>a single layer has no second layer to depend on</pm:note>\n      \
</pm:absent>\n    </pm:couplings>\n",
    );
    x.push_str("  </pm:stack>\n\n</pm:processModulus>\n");

    Emitted { notation, xml: x }
}

fn layer(run: &Run, r: &Reading, instrument: Instrument, as_of: &str) -> String {
    let s = &run.settings;
    let mut x = String::new();
    x.push_str("    <pm:layer>\n      <pm:name>line</pm:name>\n\n");

    // ---- demand ------------------------------------------------------------------------
    x.push_str("      <pm:demand>\n        <pm:amount>\n");
    // The two shapes have different authors. A single-value demand is an observed count, and
    // nobody set its edge; a ranged one has edges that came from a filer declaring how big an ask
    // can be, which is a limit somebody chose and could move.
    let demand_origin = if is_point(r.demand) {
        BoundOrigin::NotApplicable(
            "an observed count of what was asked over the window. Nothing sets its edge and \
             there is nobody to negotiate one",
        )
    } else {
        BoundOrigin::Policy
    };
    x.push_str(&claim(
        r.demand,
        Narrowing::for_bound(r.demand, instrument),
        demand_origin,
        as_of,
        12,
        "no ask was recorded, so nothing here has a size",
    ));
    x.push_str("        </pm:amount>\n");
    x.push_str("        <pm:patience>\n");
    x.push_str(&patience(s, instrument, as_of));
    x.push_str("        </pm:patience>\n      </pm:demand>\n\n");

    // ---- the time buffer ---------------------------------------------------------------
    x.push_str("      <pm:timeSlack>\n");
    x.push_str(&time_slack(run, r, instrument, as_of));
    x.push_str("      </pm:timeSlack>\n\n");

    // ---- supply ------------------------------------------------------------------------
    x.push_str("      <pm:supply>\n        <pm:label>the line</pm:label>\n");
    x.push_str("        <pm:nameplate>\n          <pm:amount>\n");
    x.push_str(&claim(
        r.nameplate,
        Narrowing::NotApplicable,
        BoundOrigin::Derivation(
            "amountOrigin",
            "`Nameplate/amountOrigin` says who could have set a different rating, one element over",
        ),
        as_of,
        12,
        "",
    ));
    x.push_str("          </pm:amount>\n");
    // The rating is the lot over the cycle, and nobody may decide otherwise, which is what
    // `intrinsic` means. A shift pattern would be `policy`; this is the machine.
    x.push_str("          <pm:amountOrigin>\n            <pm:origin>intrinsic</pm:origin>\n          \
</pm:amountOrigin>\n");
    x.push_str(&divisibility(run, as_of));
    x.push_str(&capacity_slack(s, as_of));
    x.push_str("          <pm:inventorySlack>\n");
    x.push_str(&indent(
        &claim(
            Bounded::point(s.stock_cap),
            Narrowing::NotApplicable,
            BoundOrigin::Intrinsic,
            as_of,
            0,
            "",
        ),
        12,
    ));
    x.push_str("          </pm:inventorySlack>\n        </pm:nameplate>\n");

    // ---- what was actually drawn -------------------------------------------------------
    x.push_str("        <pm:jagged>\n          <pm:draw>\n");
    x.push_str(&claim(
        r.served,
        Narrowing::NotApplicable,
        BoundOrigin::NotApplicable(
            "a count of what was actually served. Nothing sets its edge and there is nobody to \
             negotiate one",
        ),
        as_of,
        12,
        "",
    ));
    x.push_str("          </pm:draw>\n");
    x.push_str(
        "          <pm:measurementBasis>\n            <pm:absent>\n              \
<pm:reason>notApplicable</pm:reason>\n              \
<pm:note>a count of units off a line has no accounting measurement \
         basis</pm:note>\n            </pm:absent>\n          </pm:measurementBasis>\n        \
</pm:jagged>\n      </pm:supply>\n\n",
    );

    // ---- the remainder -----------------------------------------------------------------
    x.push_str(&remainder(r, as_of));
    x.push_str("    </pm:layer>\n");
    x
}

// -------------------------------------------------------------------------------------------
// The remainder, which is where the arithmetic has to close.
// -------------------------------------------------------------------------------------------

/// ISO 286 on two ranges, exactly as `layers/remainder.sqlc` computes it.
///
/// Clearance is tested first, and that order is a decision. Where a single-value nameplate equals
/// a single-value demand, both clearance and interference hold, and ISO 286's own answer for that
/// line-to-line case is a clearance fit with zero minimum clearance.
fn fit(nameplate: Bounded, demand: Bounded) -> Option<&'static str> {
    match (nameplate, demand) {
        (
            Bounded::Range {
                low: n_low,
                high: n_high,
            },
            Bounded::Range {
                low: d_low,
                high: d_high,
            },
        ) => Some(if n_low - d_high >= 0.0 {
            "clearance"
        } else if n_high - d_low <= 0.0 {
            "interference"
        } else {
            "transition"
        }),
        _ => None,
    }
}

/// How far the line can run above its rating.
///
/// `notApplicable` and zero are different answers, and the line decides which. With no overtime
/// allowance, no branch in `layer.rs` makes a lot early, so the room above the rating does not
/// exist: that is the absence of the buffer, not a measurement of nought. With an allowance the
/// figure is exact and somebody chose it, so `boundOrigin` is `policy`: it is a lever, which is
/// why a receiver wants the number.
fn capacity_slack(s: &Settings, as_of: &str) -> String {
    if s.overtime_lots == 0 {
        return "          <pm:capacitySlack>\n            <pm:absent>\n              \
                <pm:reason>notApplicable</pm:reason>\n              \
                <pm:note>the line has no way to run above its rating: a lot takes a cycle and \
                nothing shortens a cycle</pm:note>\n            </pm:absent>\n          \
                </pm:capacitySlack>\n"
            .to_string();
    }
    let mut x = String::new();
    x.push_str("          <pm:capacitySlack>\n");
    x.push_str(&indent(
        &claim(
            Bounded::point(s.capacity_slack()),
            Narrowing::NotApplicable,
            BoundOrigin::Policy,
            as_of,
            0,
            "",
        ),
        12,
    ));
    x.push_str("          </pm:capacitySlack>\n");
    x
}

fn is_point(b: Bounded) -> bool {
    matches!(b, Bounded::Range { low, high } if (high - low).abs() < 1e-9)
}

fn mode(b: Bounded) -> Option<f64> {
    match b {
        Bounded::Range { low, high } => Some((low + high) / 2.0),
        Bounded::Unmeasured => None,
    }
}

fn remainder(r: &Reading, as_of: &str) -> String {
    let mut x = String::new();
    x.push_str("      <pm:remainder>\n");

    let Some(sign) = fit(r.nameplate, r.demand) else {
        // Nothing can be said about a difference when one side was never measured.
        x.push_str(
            "        <pm:absent>\n          <pm:reason>unmeasured</pm:reason>\n          \
<pm:note>the demand was not measured, so the difference between it and \
             the rating is not either</pm:note>\n        </pm:absent>\n      </pm:remainder>\n\n",
        );
        return x;
    };

    let magnitude = (mode(r.nameplate).unwrap() - mode(r.demand).unwrap()).abs();

    x.push_str("        <pm:remainder>\n");
    x.push_str(&format!(
        "          <pm:sign><pm:fit>{sign}</pm:fit></pm:sign>\n"
    ));

    x.push_str(&absorber(r, sign));

    x.push_str(&holders(r, sign, magnitude, as_of));

    // A `magnitude` derivation, as the corpus files it: the magnitude follows from the nameplate
    // and the demand, and filing it again would state the same fact twice.
    x.push_str(&format!(
        "          <pm:quantity>\n            <pm:derivation>\n              \
<pm:identity>magnitude</pm:identity>\n              \
<pm:note>nameplate and demand are {magnitude:.2} {UNIT} apart</pm:note>\n            \
</pm:derivation>\n          </pm:quantity>\n"
    ));
    x.push_str("        </pm:remainder>\n      </pm:remainder>\n\n");
    x
}

/// The shares add up to the exact magnitude, and the note says why they differ from the raw
/// counts. What each holder bore, counted straight off the history, misses the magnitude by the
/// two terms at the edge of the window: demand still waiting at the close, and rating that never
/// became anything a customer could take. The measured shares are filed as measured, the
/// difference goes to `unrealised`, and the reconciliation is written into the filing so it can
/// be checked.
fn holders(r: &Reading, sign: &str, magnitude: f64, as_of: &str) -> String {
    let mut x = String::new();

    // A clearance excludes `customer` and `unrealised` outright: nothing went unserved.
    if sign == "clearance" {
        x.push_str(&one_holder(
            "booked",
            Bounded::point(magnitude),
            as_of,
            "rating that was put in place and not drawn on. It sits in the books as cost \
             whether or not anybody asked for it",
        ));
        return x;
    }

    let (Some(customer), Some(_unrealised)) = (mode(r.customer), mode(r.unrealised)) else {
        // What kind of loss this is, and it is not a wide range. The instrument fixed the sum of
        // these two and observed neither, so filing either as a number would be inventing
        // evidence. `shares_do_not_sum` suspends on an unstated share by design, which is right:
        // the sum is unknown, not wrong.
        x.push_str(
            "          <pm:holder>\n            <pm:absent>\n              \
<pm:reason>unmeasured</pm:reason>\n              \
<pm:note>the log records a failure with a reason and no magnitude, \
             and nothing in it distinguishes demand turned away at the door from demand that \
             waited and left. Their sum is bounded; neither part is observed</pm:note>\n            \
</pm:absent>\n          </pm:holder>\n",
        );
        return x;
    };

    // The third holder, which the simulation reaches without being told about it. What the line
    // made past its rating was made by somebody working past it, and no transaction records that.
    // It is a real cost with no financial instrument behind it, which is what `people` is for,
    // the one `pm:HolderKind` of the five that has none.
    //
    // The measured shares are filed as measured, and the reconciliation goes to the one that is
    // not measured. What the line made past its rating is known to the unit and bounded by a
    // policy; what waited past its patience is counted. Scaling them to fit the magnitude would
    // move an exact `people` share past an exact capacity slack and make a violation out of
    // rounding. The two terms at the edge of the window are demand nobody served, so they belong
    // on `unrealised`.
    let ran_hot = mode(r.ran_hot).unwrap_or(0.0);
    let note = format!(
        "the two measured shares are filed as measured and the window-boundary residue lands \
         here: the remainder is {magnitude:.2}, of which {ran_hot:.2} was made past the rating and \
         {customer:.2} waited past its patience"
    );

    let mut left = magnitude;
    if ran_hot > 1e-9 {
        left -= ran_hot;
        x.push_str(&one_holder(
            "people",
            Bounded::point(ran_hot),
            as_of,
            "made past the rating by whoever was on the line. No transaction records it and no \
             instrument measures it, which is the one holder of the five with no financial \
             instrument behind it",
        ));
    }
    if customer > 1e-9 {
        left -= customer;
        x.push_str(&one_holder(
            "customer",
            Bounded::point(customer),
            as_of,
            "waited past its patience and left",
        ));
    }
    // A negative amount left here would mean the measured shares already exceed the magnitude,
    // which is a contradiction in the arithmetic rather than a fact about the run. The generator
    // fails loudly rather than file a negative share.
    assert!(
        left > -1e-6,
        "the measured shares exceed the remainder by {:.4}",
        -left
    );
    x.push_str(&one_holder(
        "unrealised",
        Bounded::point(left.max(0.0)),
        as_of,
        &format!("turned away at the door, so nobody ever experienced it. {note}"),
    ));
    x
}

/// Which of the three buffers took the remainder.
///
/// The schema names one buffer, and on a clearance layer that matters: the line both idled and
/// held finished stock, so two buffers absorbed parts of one remainder and only one may be named.
/// `capacity` is named, because idle rating is the larger by an order of magnitude here, and
/// because the schema says idle capacity is the capacity buffer.
///
/// On an interference layer the answer depends on the instrument. Whether an ask was met from
/// stock or only after queuing is a fact about its wait, and a stock-and-flow log carries no wait.
/// So the same run files a named absorber under one instrument and `unmeasured` under the other,
/// and neither document is wrong. Naming `time` there would be a claim no evidence in that filing
/// supports, and no rule would catch it.
fn absorber(r: &Reading, sign: &str) -> String {
    let term = |value: &str| {
        format!(
            "          <pm:absorber>\n            <pm:term>\n              \
             <pm:taxonomy>{BUFFERS}</pm:taxonomy>\n              \
             <pm:value>{value}</pm:value>\n            </pm:term>\n          </pm:absorber>\n"
        )
    };
    if sign == "clearance" {
        return term("capacity");
    }
    // The question is which buffer took the remainder, not which did the most work. On an
    // overtime run the queue serves more demand than overtime does, yet demand that was served,
    // out of stock or after waiting, is not part of the remainder at all. The only part of the
    // remainder anybody absorbed is what the line made past its rating. Naming `time` there would
    // set the overtime share against the time buffer's slack, and `share_exceeds_slack` would
    // rightly fire.
    let hot = mode(r.ran_hot).unwrap_or(0.0);
    if hot > 1e-9 {
        return term("capacity");
    }
    // Nothing absorbed it, and `none` says so. Every unit of this remainder went unserved, so
    // there is no buffer to name and no share for a rule to bound. `none` is somebody looking and
    // finding no absorber, which is a different claim from naming whichever buffer was at hand.
    match (mode(r.from_stock), mode(r.after_waiting)) {
        (Some(_), Some(_)) => "          <pm:absorber>\n            <pm:absent>\n              \
             <pm:reason>none</pm:reason>\n              \
             <pm:note>every unit of this remainder went unserved. The line ran no faster than \
             its rating, so no buffer took any of it</pm:note>\n            </pm:absent>\n          \
             </pm:absorber>\n"
            .to_string(),
        _ => "          <pm:absorber>\n            <pm:absent>\n              \
              <pm:reason>unmeasured</pm:reason>\n              \
              <pm:note>no wait is recorded against a demand, so nothing here says whether an \
              ask was met out of stock or only after queuing</pm:note>\n            \
              </pm:absent>\n          </pm:absorber>\n"
            .to_string(),
    }
}

fn one_holder(kind: &str, share: Bounded, as_of: &str, note: &str) -> String {
    let mut x = String::new();
    x.push_str("          <pm:holder>\n            <pm:holder>\n");
    x.push_str(&format!("              <pm:kind>{kind}</pm:kind>\n"));
    x.push_str("              <pm:share>\n");
    x.push_str(&indent(
        &claim(
            share,
            Narrowing::NotApplicable,
            BoundOrigin::NotApplicable(note),
            as_of,
            0,
            "",
        ),
        16,
    ));
    x.push_str("              </pm:share>\n            </pm:holder>\n          </pm:holder>\n");
    x
}

// -------------------------------------------------------------------------------------------
// The pieces every claim is made of.
// -------------------------------------------------------------------------------------------

enum Narrowing {
    /// A single value has no width to tighten.
    NotApplicable,
    /// A generator knows which setting made the spread, so it can always fill this field: a bound
    /// that came from an instrument that did not record something narrows when the instrument is
    /// changed, and never by running again.
    Instrument(&'static str),
}

impl Narrowing {
    fn for_bound(b: Bounded, instrument: Instrument) -> Narrowing {
        match (b, instrument) {
            (Bounded::Range { low, high }, _) if (high - low).abs() < 1e-9 => {
                Narrowing::NotApplicable
            }
            (_, Instrument::StockAndFlow) => Narrowing::Instrument(
                "a refusal is logged with the quantity it turned away, rather than a reason \
                 alone",
            ),
            (_, Instrument::Whole) => Narrowing::NotApplicable,
        }
    }

    fn xml(&self, pad: usize) -> String {
        let p = " ".repeat(pad);
        match self {
            Narrowing::NotApplicable => format!(
                "{p}<pm:narrowsWhen><pm:absent><pm:reason>notApplicable</pm:reason>\
                 <pm:note>there is no range here to tighten</pm:note></pm:absent>\
                 </pm:narrowsWhen>\n"
            ),
            Narrowing::Instrument(condition) => format!(
                "{p}<pm:narrowsWhen>\n{p}  <pm:narrowing>\n{p}    \
                 <pm:condition>{condition}</pm:condition>\n{p}    \
                 <pm:kind>instrument</pm:kind>\n{p}  </pm:narrowing>\n{p}</pm:narrowsWhen>\n"
            ),
        }
    }
}

/// Who owns the edge of a claim.
///
/// There is no `none` variant, on purpose. `none` says the bound is where the measurements fell,
/// which describes a spread a single-value claim does not have, and `bound_fell_with_no_range`
/// rejects it there. The true answer for an exact observation is `notApplicable`. Without the
/// variant, the generator cannot make that mistake.
enum BoundOrigin<'a> {
    Intrinsic,
    Policy,
    NotApplicable(&'a str),
    /// The identity that names the author, and a note.
    Derivation(&'a str, &'a str),
}

impl BoundOrigin<'_> {
    fn xml(&self, pad: usize) -> String {
        let p = " ".repeat(pad);
        let absent = |reason: &str, note: &str| {
            format!(
                "{p}<pm:boundOrigin><pm:absent><pm:reason>{reason}</pm:reason>\
                 <pm:note>{note}</pm:note></pm:absent></pm:boundOrigin>\n"
            )
        };
        match self {
            BoundOrigin::Intrinsic => {
                format!("{p}<pm:boundOrigin><pm:origin>intrinsic</pm:origin></pm:boundOrigin>\n")
            }
            BoundOrigin::Policy => {
                format!("{p}<pm:boundOrigin><pm:origin>policy</pm:origin></pm:boundOrigin>\n")
            }
            BoundOrigin::NotApplicable(note) => absent("notApplicable", note),
            BoundOrigin::Derivation(identity, note) => format!(
                "{p}<pm:boundOrigin><pm:derivation><pm:identity>{identity}</pm:identity>\
                 <pm:note>{note}</pm:note></pm:derivation></pm:boundOrigin>\n"
            ),
        }
    }
}

/// One `pm:StatedClaim`, or the typed absence where the instrument had nothing.
fn claim(
    b: Bounded,
    narrows: Narrowing,
    origin: BoundOrigin<'_>,
    as_of: &str,
    pad: usize,
    absent_note: &str,
) -> String {
    let p = " ".repeat(pad);
    let (low, high) = match b {
        Bounded::Range { low, high } => (low, high),
        Bounded::Unmeasured => {
            return format!(
                "{p}<pm:absent>\n{p}  <pm:reason>unmeasured</pm:reason>\n{p}  \
                 <pm:note>{absent_note}</pm:note>\n{p}</pm:absent>\n"
            );
        }
    };
    let ml = (low + high) / 2.0;
    let mut x = String::new();
    x.push_str(&format!("{p}<pm:claim>\n"));
    x.push_str(&format!(
        "{p}  <pm:low>{low:.4}</pm:low><pm:mostLikely>{ml:.4}</pm:mostLikely>\
         <pm:high>{high:.4}</pm:high>\n"
    ));
    x.push_str(&format!("{p}  <pm:unit>{UNIT}</pm:unit>\n"));
    x.push_str(&format!(
        "{p}  <pm:denominator><pm:period>{PERIOD}</pm:period></pm:denominator>\n"
    ));
    x.push_str(&narrows.xml(pad + 2));
    x.push_str(&origin.xml(pad + 2));
    x.push_str(&format!(
        "{p}  <pm:provenance><pm:party>bench</pm:party>\n{p}    \
         <pm:standing><pm:term><pm:taxonomy>urn:example:assertion-standing:2026</pm:taxonomy>\
         <pm:value>generated</pm:value></pm:term></pm:standing>\n{p}  </pm:provenance>\n"
    ));
    x.push_str(&format!("{p}  <pm:asOf>{as_of}</pm:asOf>\n"));
    x.push_str(&format!("{p}</pm:claim>\n"));
    x
}

/// A bench knows its patience by construction, because it is a parameter of the run.
fn patience(s: &Settings, instrument: Instrument, as_of: &str) -> String {
    if instrument == Instrument::StockAndFlow {
        // A resource that waits for ever has no patience to record, so this is not a
        // measurement anybody omitted but a notion the instrument lacks.
        return "          <pm:absent>\n            <pm:reason>unmeasured</pm:reason>\n            \
<pm:note>nothing in a stock-and-flow log gives a queued demand a \
                lifetime, so how long one survives being unanswered is not recorded</pm:note>\n          \
</pm:absent>\n"
            .to_string();
    }
    // Zero patience is a claim of zero, not an absence. `Demand/patience` is a `StatedClaim`, so
    // its absence is a `ClaimAbsence`, and `ClaimAbsenceReason` has no `none`. That is right:
    // somebody measured how long this demand survives being held and the answer was nothing,
    // which is a measurement rather than a missing column.
    //
    // A patience is a span of time and not the layer's unit, which is what separates it from
    // `timeSlack`. It bounds no shares, so `slack_unit_mismatch` does not reach it.
    let secs = s.patience.as_secs_f64();
    format!(
        "          <pm:claim>\n            <pm:low>{secs:.1}</pm:low>\
         <pm:mostLikely>{secs:.1}</pm:mostLikely><pm:high>{secs:.1}</pm:high>\n            \
<pm:unit>seconds</pm:unit>\n            \
<pm:denominator><pm:absent><pm:reason>notApplicable</pm:reason>\
         </pm:absent></pm:denominator>\n            \
<pm:narrowsWhen><pm:absent><pm:reason>notApplicable</pm:reason>\
         <pm:note>there is no range here to tighten</pm:note></pm:absent></pm:narrowsWhen>\n            \
<pm:boundOrigin><pm:origin>policy</pm:origin></pm:boundOrigin>\n            \
<pm:asOf>{as_of}</pm:asOf>\n          </pm:claim>\n"
    )
}

/// The time buffer, in the layer's unit rather than in seconds.
///
/// The patience in seconds is multiplied by the demand rate to give a quantity in the layer's
/// unit. Once done, that step cannot be seen, so the note says it. `slack_unit_mismatch` requires
/// a slack in the unit of the shares it bounds, and a slack that skips the multiplication and
/// keeps the right unit is caught by nothing.
fn time_slack(run: &Run, r: &Reading, instrument: Instrument, as_of: &str) -> String {
    let s = &run.settings;
    if instrument == Instrument::StockAndFlow {
        return "        <pm:absent>\n          <pm:reason>unmeasured</pm:reason>\n          \
<pm:note>no wait is recorded against a demand, because no demand is \
                recorded until it succeeds</pm:note>\n        </pm:absent>\n"
            .to_string();
    }
    let Some(demand) = mode(r.demand) else {
        return "        <pm:absent>\n          <pm:reason>unmeasured</pm:reason>\n          \
<pm:note>the rate the wait would be multiplied by is not \
                measured</pm:note>\n        </pm:absent>\n"
            .to_string();
    };
    let rate = demand / run.window.as_secs_f64();
    let quantity = s.patience.as_secs_f64() * rate;
    let mut x = String::new();
    x.push_str("        <pm:claim>\n");
    x.push_str(&format!(
        "          <pm:low>{quantity:.4}</pm:low><pm:mostLikely>{quantity:.4}</pm:mostLikely>\
         <pm:high>{quantity:.4}</pm:high>\n"
    ));
    x.push_str(&format!("          <pm:unit>{UNIT}</pm:unit>\n"));
    x.push_str(&format!(
        "          <pm:denominator><pm:period>{PERIOD}</pm:period></pm:denominator>\n"
    ));
    x.push_str(&Narrowing::NotApplicable.xml(10));
    x.push_str("          <pm:boundOrigin><pm:origin>policy</pm:origin></pm:boundOrigin>\n");
    x.push_str(&format!(
        "          <pm:provenance><pm:party>bench</pm:party>\n            \
         <pm:standing><pm:term><pm:taxonomy>urn:example:assertion-standing:2026</pm:taxonomy>\
         <pm:value>generated</pm:value></pm:term></pm:standing>\n            \
         <pm:note>a patience of {p:.0} seconds at a demand rate of {rate:.4} {UNIT} per second \
         is {quantity:.2} {UNIT}. The multiplication is the bridge from the duration that was \
         measured to the quantity the field takes</pm:note>\n          </pm:provenance>\n",
        p = s.patience.as_secs_f64()
    ));
    x.push_str(&format!("          <pm:asOf>{as_of}</pm:asOf>\n        </pm:claim>\n"));
    x
}

/// The quantum, and the part of the period the line is live for.
fn divisibility(run: &Run, as_of: &str) -> String {
    let s = &run.settings;
    let mut x = String::new();
    x.push_str("          <pm:divisibility>\n            <pm:divisibility>\n");
    x.push_str("              <pm:lumpy>\n                <pm:size>\n");
    // The quantum is in the unit of the nameplate it divides, and this nameplate is a rate, so
    // the demand and the nameplate divided by it are counts of lots.
    x.push_str(&indent(
        &claim(
            Bounded::point(s.lot),
            Narrowing::NotApplicable,
            BoundOrigin::Derivation(
                "quantumOrigin",
                "`LumpyQuantum/origin` says who sets the size of one unit, in this same element",
            ),
            as_of,
            0,
            "",
        ),
        18,
    ));
    x.push_str("                </pm:size>\n");
    x.push_str("                <pm:origin>intrinsic</pm:origin>\n              </pm:lumpy>\n");
    // The time the line is live, not the gap. The line runs the whole shift without stopping, so
    // it is live for all of it and the window is the period.
    let hours = run.window.as_secs_f64() / 3600.0;
    x.push_str(&format!(
        "              <pm:window>\n                <pm:quantum>\n                  \
         <pm:size>\n                    <pm:claim>\n                      \
         <pm:low>{hours:.1}</pm:low><pm:mostLikely>{hours:.1}</pm:mostLikely>\
         <pm:high>{hours:.1}</pm:high>\n                      \
         <pm:unit>hours</pm:unit>\n                      \
         <pm:denominator><pm:period>{PERIOD}</pm:period></pm:denominator>\n                      \
         <pm:narrowsWhen><pm:absent><pm:reason>notApplicable</pm:reason>\
         <pm:note>there is no range here to tighten</pm:note></pm:absent></pm:narrowsWhen>\n                      \
<pm:boundOrigin><pm:origin>intrinsic</pm:origin>\
         </pm:boundOrigin>\n                      <pm:asOf>{as_of}</pm:asOf>\n                    \
         </pm:claim>\n                  </pm:size>\n                  \
         <pm:origin>intrinsic</pm:origin>\n                </pm:quantum>\n              \
         </pm:window>\n"
    ));
    x.push_str("            </pm:divisibility>\n          </pm:divisibility>\n");
    x
}

fn indent(block: &str, pad: usize) -> String {
    let p = " ".repeat(pad);
    block
        .lines()
        .map(|l| if l.is_empty() { l.to_string() } else { format!("{p}{l}") })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}
