//! A reading written out as `pm:processModulus`.
//!
//! ⭐⭐⭐ THE FILING IS EMITTED FROM A READING, NEVER FROM THE HISTORY. That is the whole
//! arrangement: the instrument decides what is knowable and the emitter only writes down what
//! the instrument returned. Two filings therefore come out of one run, and the rules in
//! `assets/sql/checks/` get to say whether an honest report of ignorance is a contradiction.
//!
//! ⛔⛔ WHAT THE SHARES HAVE TO SUM TO IS EXACT, AND MAKING IT SO SURFACED TWO THINGS PROSE
//! WOULD HAVE MISSED. `shares_do_not_sum` compares against `|n - d|` at the mode with a
//! tolerance of `1e-9`, so a partition that is nearly right is a violation. It is nearly right
//! for two reasons and both are real:
//!
//!   pending      demand that had arrived and was still waiting when the window closed. It is
//!                neither served nor unserved and no `pm:HolderKind` fits it, because nobody
//!                has borne anything yet.
//!   undelivered  rating that never became something a customer could take. On a short layer
//!                this is the RESIDUE: supply too small to meet any whole ask, which is
//!                `r ≡ -demand (mod q)` showing up as a number.
//!
//! The shares below are therefore a proportional partition of the exact magnitude, with the
//! reconciliation written into the filing as a note so a reader can check the arithmetic.

use super::instrument::{Bounded, Instrument, Reading};
use super::layer::Settings;
use super::window::Run;

/// The unit every claim in a generated filing is quoted in.
///
/// ⭐ A RATE, AND THE DENOMINATOR IS WHY. `Claim/denominator` exists so that
/// `Divisibility/window` has a well defined period to be a fraction of, and a nameplate quoted
/// as a bare count has no cycle to run on.
const UNIT: &str = "units per shift";
const PERIOD: &str = "shift";

/// Which buffers the Factory Physics term comes from.
const BUFFERS: &str = "urn:example:factory-physics:buffers";

pub struct Emitted {
    pub notation: String,
    pub xml: String,
}

/// Writes one run, as one instrument read it, into one filing.
///
/// ⛔ `case` IS PART OF THE NOTATION AND HAS TO BE. `filing_identity` is keyed on the URN, so two
/// runs of the same bench at the same seed under different settings would collide on ingest. The
/// schema's own identity constraint found that within a minute of the first load, which is the
/// keyref doing exactly what `assets/sqlc/README.md` says the corpus cannot do for itself.
pub fn emit(run: &Run, reading: &Reading, instrument: Instrument, case: &str, as_of: &str) -> Emitted {
    let kind = match instrument {
        Instrument::Whole => "whole",
        Instrument::StockAndFlow => "stock-and-flow",
    };
    let notation = format!(
        "urn:example:filing:bench:{case}:{kind}:seed-{seed}",
        seed = run.seed
    );

    let mut x = String::new();
    x.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    x.push_str(&format!(
        "<!--\n  GENERATED by examples/shared/simulation, from a NeXosim bench. Do not edit.\n\
n  Instrument: {kind}. {}\n-->\n",
        match instrument {
            Instrument::Whole =>
                "Every field of every event was available, so what is absent here is absent \
                 because the model has no branch for it.",
            Instrument::StockAndFlow =>
                "Only what a stock-and-flow event log records was available: successes with \
                 their totals, failures with a reason and no magnitude, and no event at all \
                 for a demand that gave up waiting.",
        }
    ));
    x.push_str("<pm:processModulus xmlns:pm=\"https://example.invalid/process-flow/1.0\">\n\n");

    x.push_str(&format!(
        "  <pm:notation>\n    <pm:uri>{notation}</pm:uri>\n  </pm:notation>\n"
    ));
    // ⭐ AN OBSERVATION, NOT A STIPULATION. Nobody asserted these figures; a bench ran and they
    //   were counted off it. That the bench is itself a model is a fact about the SUBJECT, not
    //   about how the numbers were come by.
    x.push_str("  <pm:evidence>\n    <pm:attests>observation</pm:attests>\n  </pm:evidence>\n\n");

    x.push_str("  <pm:stack>\n");
    x.push_str(&format!(
        "    <pm:scope>\n      <pm:scope>\n        <pm:extent>scoped</pm:extent>\n        \
<pm:basis>one line over one shift of {hours} hours, generated by \
         examples/shared/simulation at seed {seed}</pm:basis>\n      </pm:scope>\n    </pm:scope>\n",
        hours = run.window.as_secs() / 3600,
        seed = run.seed
    ));

    x.push_str(&layer(run, reading, instrument, as_of));

    // ⛔ ONE LAYER HAS NOTHING TO COUPLE TO. `notApplicable` rather than `none`, because `none`
    //   would say somebody looked for a dependence between two layers and there is only one.
    x.push_str(
        "    <pm:couplings>\n      <pm:absent>\n        <pm:reason>notApplicable</pm:reason>\n        \
<pm:note>a single layer has no second layer to depend on</pm:note>\n      \
</pm:absent>\n    </pm:couplings>\n",
    );
    x.push_str("  </pm:stack>\n\n</pm:processModulus>\n");

    Emitted { notation, xml: x }
}

fn layer(run: &Run, r: &Reading, instrument: Instrument, as_of: &str) -> String {
    let s = &run.settings;
    let mut x = String::new();
    x.push_str("    <pm:layer>\n      <pm:name>line</pm:name>\n\n");

    // ---- demand ------------------------------------------------------------------------
    x.push_str("      <pm:demand>\n        <pm:amount>\n");
    // ⭐ THE TWO SHAPES HAVE DIFFERENT AUTHORS. A point demand is an observed count and nobody
    //   set its edge; a ranged one has edges that came from a filer declaring how big an ask can
    //   be, which is a limit somebody chose and could move.
    let demand_origin = if is_point(r.demand) {
        BoundOrigin::NotApplicable(
            "an observed count of what was asked over the window. Nothing sets its edge and \
             there is nobody to negotiate one",
        )
    } else {
        BoundOrigin::Policy
    };
    x.push_str(&claim(
        r.demand,
        Narrowing::for_bound(r.demand, instrument),
        demand_origin,
        as_of,
        12,
        "no ask was recorded, so nothing here has a size",
    ));
    x.push_str("        </pm:amount>\n");
    x.push_str("        <pm:patience>\n");
    x.push_str(&patience(s, instrument, as_of));
    x.push_str("        </pm:patience>\n      </pm:demand>\n\n");

    // ---- the time buffer ---------------------------------------------------------------
    x.push_str("      <pm:timeSlack>\n");
    x.push_str(&time_slack(run, r, instrument, as_of));
    x.push_str("      </pm:timeSlack>\n\n");

    // ---- supply ------------------------------------------------------------------------
    x.push_str("      <pm:supply>\n        <pm:label>the line</pm:label>\n");
    x.push_str("        <pm:nameplate>\n          <pm:amount>\n");
    x.push_str(&claim(
        r.nameplate,
        Narrowing::NotApplicable,
        BoundOrigin::Derived("`Nameplate/amountOrigin` says who could have set a different \
                              rating, one element over"),
        as_of,
        12,
        "",
    ));
    x.push_str("          </pm:amount>\n");
    // ⭐ THE RATING IS THE LOT OVER THE CYCLE AND NOBODY MAY DECIDE OTHERWISE, which is what
    //   `intrinsic` means. A shift pattern would be `policy`; this is the machine.
    x.push_str("          <pm:amountOrigin>\n            <pm:origin>intrinsic</pm:origin>\n          \
</pm:amountOrigin>\n");
    x.push_str(&divisibility(run, as_of));
    x.push_str(&capacity_slack(s, as_of));
    x.push_str("          <pm:inventorySlack>\n");
    x.push_str(&indent(
        &claim(
            Bounded::point(s.stock_cap),
            Narrowing::NotApplicable,
            BoundOrigin::Intrinsic,
            as_of,
            0,
            "",
        ),
        12,
    ));
    x.push_str("          </pm:inventorySlack>\n        </pm:nameplate>\n");

    // ---- what was actually drawn -------------------------------------------------------
    x.push_str("        <pm:jagged>\n          <pm:draw>\n");
    x.push_str(&claim(
        r.served,
        Narrowing::NotApplicable,
        BoundOrigin::NotApplicable(
            "a count of what was actually served. Nothing sets its edge and there is nobody to \
             negotiate one",
        ),
        as_of,
        12,
        "",
    ));
    x.push_str("          </pm:draw>\n");
    x.push_str(
        "          <pm:measurementBasis>\n            <pm:absent>\n              \
<pm:reason>notApplicable</pm:reason>\n              \
<pm:note>a count of units off a line has no accounting measurement \
         basis</pm:note>\n            </pm:absent>\n          </pm:measurementBasis>\n        \
</pm:jagged>\n      </pm:supply>\n\n",
    );

    // ---- the remainder -----------------------------------------------------------------
    x.push_str(&remainder(r, as_of));
    x.push_str("    </pm:layer>\n");
    x
}

// -------------------------------------------------------------------------------------------
// The remainder, which is where the arithmetic has to close.
// -------------------------------------------------------------------------------------------

/// ISO 286 on two ranges, exactly as `layers/remainder.sqlc` computes it.
///
/// ⭐ CLEARANCE IS TESTED FIRST AND THAT ORDER IS A DECISION. At a point nameplate equal to a
/// point demand all three criteria admit, and ISO 286's own answer for the line-to-line case is
/// a clearance fit with zero minimum clearance.
fn fit(nameplate: Bounded, demand: Bounded) -> Option<&'static str> {
    match (nameplate, demand) {
        (
            Bounded::Range {
                low: n_low,
                high: n_high,
            },
            Bounded::Range {
                low: d_low,
                high: d_high,
            },
        ) => Some(if n_low - d_high >= 0.0 {
            "clearance"
        } else if n_high - d_low <= 0.0 {
            "interference"
        } else {
            "transition"
        }),
        _ => None,
    }
}

/// How far the line can run above its rating.
///
/// ⛔⛔ `notApplicable` AND ZERO ARE DIFFERENT ANSWERS AND THE LINE DECIDES WHICH. With no
/// overtime allowance there is no branch in `layer.rs` that makes a lot early, so the room above
/// the rating does not exist; that is the absence of the buffer, not a measurement of nought. With
/// an allowance the figure is exact and somebody chose it, so `boundOrigin` is `policy`: it is a
/// lever, which is the whole reason a receiver would want the number.
fn capacity_slack(s: &Settings, as_of: &str) -> String {
    if s.overtime_lots == 0 {
        return "          <pm:capacitySlack>\n            <pm:absent>\n              \
                <pm:reason>notApplicable</pm:reason>\n              \
                <pm:note>the line has no way to run above its rating: a lot takes a cycle and \
                nothing shortens a cycle</pm:note>\n            </pm:absent>\n          \
                </pm:capacitySlack>\n"
            .to_string();
    }
    let mut x = String::new();
    x.push_str("          <pm:capacitySlack>\n");
    x.push_str(&indent(
        &claim(
            Bounded::point(s.capacity_slack()),
            Narrowing::NotApplicable,
            BoundOrigin::Policy,
            as_of,
            0,
            "",
        ),
        12,
    ));
    x.push_str("          </pm:capacitySlack>\n");
    x
}

fn is_point(b: Bounded) -> bool {
    matches!(b, Bounded::Range { low, high } if (high - low).abs() < 1e-9)
}

fn mode(b: Bounded) -> Option<f64> {
    match b {
        Bounded::Range { low, high } => Some((low + high) / 2.0),
        Bounded::Unmeasured => None,
    }
}

fn remainder(r: &Reading, as_of: &str) -> String {
    let mut x = String::new();
    x.push_str("      <pm:remainder>\n");

    let Some(sign) = fit(r.nameplate, r.demand) else {
        // Nothing can be said about a difference when one side was never measured.
        x.push_str(
            "        <pm:absent>\n          <pm:reason>unmeasured</pm:reason>\n          \
<pm:note>the demand was not measured, so the difference between it and \
             the rating is not either</pm:note>\n        </pm:absent>\n      </pm:remainder>\n\n",
        );
        return x;
    };

    let magnitude = (mode(r.nameplate).unwrap() - mode(r.demand).unwrap()).abs();

    x.push_str("        <pm:remainder>\n");
    x.push_str(&format!(
        "          <pm:sign><pm:fit>{sign}</pm:fit></pm:sign>\n"
    ));

    x.push_str(&absorber(r, sign));

    x.push_str(&holders(r, sign, magnitude, as_of));

    // ⭐ DERIVED, WHICH IS THE CORPUS'S OWN CONVENTION: the magnitude follows from the nameplate
    //   and the demand, and filing it again is reading the same fact twice.
    x.push_str(&format!(
        "          <pm:quantity>\n            <pm:absent>\n              \
<pm:reason>derived</pm:reason>\n              \
<pm:note>|nameplate - demand| = {magnitude:.2} {UNIT}</pm:note>\n            \
</pm:absent>\n          </pm:quantity>\n"
    ));
    x.push_str("        </pm:remainder>\n      </pm:remainder>\n\n");
    x
}

/// ⛔⛔ THE SHARES ARE A PROPORTIONAL PARTITION OF THE EXACT MAGNITUDE, AND THE NOTE SAYS WHY
/// THAT IS NOT THE SAME AS THE RAW COUNTS. What each holder bore, counted straight off the
/// history, misses `|n - d|` by the two window-boundary terms: demand still waiting at the close
/// and rating that never became anything a customer could take. Scaling keeps the observed ratio
/// and closes the sum; writing the reconciliation into the filing keeps it checkable.
fn holders(r: &Reading, sign: &str, magnitude: f64, as_of: &str) -> String {
    let mut x = String::new();

    // A clearance excludes `customer` and `unrealised` outright: nothing went unserved.
    if sign == "clearance" {
        x.push_str(&one_holder(
            "booked",
            Bounded::point(magnitude),
            as_of,
            "rating that was put in place and not drawn on. It sits in the books as cost \
             whether or not anybody asked for it",
        ));
        return x;
    }

    let (Some(customer), Some(_unrealised)) = (mode(r.customer), mode(r.unrealised)) else {
        // ⭐⭐⭐ THE SHAPE OF THE LOSS, AND IT IS NOT A WIDE RANGE. The instrument pinned the
        //    sum of these two and observed neither, so filing either as a number would be
        //    inventing evidence. `shares_do_not_sum` suspends on an unstated share by design,
        //    which is exactly the right behaviour: the sum is unknown, not wrong.
        x.push_str(
            "          <pm:holder>\n            <pm:absent>\n              \
<pm:reason>unmeasured</pm:reason>\n              \
<pm:note>the log records a failure with a reason and no magnitude, \
             and nothing in it distinguishes demand turned away at the door from demand that \
             waited and left. Their sum is bounded; neither part is observed</pm:note>\n            \
</pm:absent>\n          </pm:holder>\n",
        );
        return x;
    };

    // ⭐⭐⭐ THE THIRD HOLDER, AND IT IS THE MODEL'S OWN THESIS ARRIVING FROM A SIMULATION THAT
    //    WAS NEVER TOLD ABOUT IT. What the line made past its rating was made by somebody working
    //    past it, and no transaction anywhere records that. It is a real cost with no financial
    //    instrument, which is precisely what `people` is for and the one `pm:HolderKind` of the
    //    five that has none.
    // ⛔⛔⛔ THE MEASURED SHARES ARE FILED AS MEASURED AND THE RECONCILIATION GOES TO THE FUZZY
    //    ONE. An earlier draft scaled all three proportionally to make them sum to `|n - d|`,
    //    which pushed a `people` share of exactly 300 up past a capacity slack of exactly 300 and
    //    manufactured a violation out of rounding. What the line made past its rating is known to
    //    the unit and is bounded by a policy; what waited past its patience is counted. The two
    //    window-boundary terms are demand nobody served, so they belong on `unrealised`, which is
    //    where the arithmetic puts them anyway.
    let ran_hot = mode(r.ran_hot).unwrap_or(0.0);
    let note = format!(
        "the two measured shares are filed as measured and the window-boundary residue lands \
         here: |n - d| is {magnitude:.2}, of which {ran_hot:.2} was made past the rating and \
         {customer:.2} waited past its patience"
    );

    let mut left = magnitude;
    if ran_hot > 1e-9 {
        left -= ran_hot;
        x.push_str(&one_holder(
            "people",
            Bounded::point(ran_hot),
            as_of,
            "made past the rating by whoever was on the line. No transaction records it and no \
             instrument measures it, which is the one holder of the five with no financial \
             instrument behind it",
        ));
    }
    if customer > 1e-9 {
        left -= customer;
        x.push_str(&one_holder(
            "customer",
            Bounded::point(customer),
            as_of,
            "waited past its patience and left",
        ));
    }
    // ⚠️ A NEGATIVE REMAINDER HERE WOULD MEAN THE MEASURED SHARES ALREADY EXCEED `|n - d|`, which
    //   is an arithmetic contradiction in the fold rather than a fact about the run. Better to
    //   fail loudly in the generator than to file a negative share.
    assert!(
        left > -1e-6,
        "the measured shares exceed |n - d| by {:.4}",
        -left
    );
    x.push_str(&one_holder(
        "unrealised",
        Bounded::point(left.max(0.0)),
        as_of,
        &format!("turned away at the door, so nobody ever experienced it. {note}"),
    ));
    x
}

/// Which of the three buffers took the remainder.
///
/// ⛔⛔ THE SINGULAR IS THE SCHEMA'S AND IT BITES ON A CLEARANCE LAYER, where the line both idled
/// and held finished stock, so two buffers absorbed parts of one remainder and only one may be
/// named. `capacity` is named because idle rating is the larger by an order of magnitude here and
/// because the schema is explicit that idle capacity IS the capacity buffer.
///
/// ⭐⭐⭐ AND ON AN INTERFERENCE LAYER THE ANSWER DEPENDS ON THE INSTRUMENT, WHICH IS THE WHOLE
/// LESSON. Whether an ask was met from stock or only after queuing is a fact about its wait, and a
/// stock-and-flow log carries no wait. So the same run files a named absorber under one instrument
/// and `unmeasured` under the other, and neither document is wrong. Guessing `time` here, which an
/// earlier draft did, is a claim no evidence in that filing supports and no rule would have caught.
fn absorber(r: &Reading, sign: &str) -> String {
    let term = |value: &str| {
        format!(
            "          <pm:absorber>\n            <pm:term>\n              \
             <pm:taxonomy>{BUFFERS}</pm:taxonomy>\n              \
             <pm:value>{value}</pm:value>\n            </pm:term>\n          </pm:absorber>\n"
        )
    };
    if sign == "clearance" {
        return term("capacity");
    }
    // ⛔⛔⛔ THE QUESTION IS WHICH BUFFER TOOK THE REMAINDER, NOT WHICH DID THE MOST WORK, AND AN
    //    EARLIER DRAFT ANSWERED THE SECOND. It named `time` on an overtime run because the queue
    //    served more demand than overtime did, and `share_exceeds_slack` fired: 304 attributed to
    //    a time buffer whose slack is 67. The rule was right and the filing was wrong. Demand
    //    that was SERVED, out of stock or after waiting, is not part of `|n - d|` at all. The only
    //    part of the remainder anybody absorbed is what the line made past its rating.
    let hot = mode(r.ran_hot).unwrap_or(0.0);
    if hot > 1e-9 {
        return term("capacity");
    }
    // ⭐ NOTHING ABSORBED IT, AND `none` SAYS SO. Every unit of this remainder went unserved, so
    //   there is no buffer to name and no share for a rule to bound. `none` is somebody looking
    //   and finding no absorber, which is a different claim from naming the buffer that happened
    //   to be on the table.
    match (mode(r.from_stock), mode(r.after_waiting)) {
        (Some(_), Some(_)) => "          <pm:absorber>\n            <pm:absent>\n              \
             <pm:reason>none</pm:reason>\n              \
             <pm:note>every unit of this remainder went unserved. The line ran no faster than \
             its rating, so no buffer took any of it</pm:note>\n            </pm:absent>\n          \
             </pm:absorber>\n"
            .to_string(),
        _ => "          <pm:absorber>\n            <pm:absent>\n              \
              <pm:reason>unmeasured</pm:reason>\n              \
              <pm:note>no wait is recorded against a demand, so nothing here says whether an \
              ask was met out of stock or only after queuing</pm:note>\n            \
              </pm:absent>\n          </pm:absorber>\n"
            .to_string(),
    }
}

fn one_holder(kind: &str, share: Bounded, as_of: &str, note: &str) -> String {
    let mut x = String::new();
    x.push_str("          <pm:holder>\n            <pm:holder>\n");
    x.push_str(&format!("              <pm:kind>{kind}</pm:kind>\n"));
    x.push_str("              <pm:share>\n");
    x.push_str(&indent(
        &claim(
            share,
            Narrowing::NotApplicable,
            BoundOrigin::NotApplicable(note),
            as_of,
            0,
            "",
        ),
        16,
    ));
    x.push_str("              </pm:share>\n            </pm:holder>\n          </pm:holder>\n");
    x
}

// -------------------------------------------------------------------------------------------
// The pieces every claim is made of.
// -------------------------------------------------------------------------------------------

enum Narrowing {
    /// A point has no width to tighten.
    NotApplicable,
    /// ⭐⭐⭐ FILLED BY CONSTRUCTION, WHICH IS THE FIELD THE CORPUS IS WEAKEST ON. A generator
    /// knows which knob made the spread: a bound that came from an instrument that did not
    /// record something narrows when the instrument is changed, and never by running again.
    Instrument(&'static str),
}

impl Narrowing {
    fn for_bound(b: Bounded, instrument: Instrument) -> Narrowing {
        match (b, instrument) {
            (Bounded::Range { low, high }, _) if (high - low).abs() < 1e-9 => {
                Narrowing::NotApplicable
            }
            (_, Instrument::StockAndFlow) => Narrowing::Instrument(
                "a refusal is logged with the quantity it turned away, rather than a reason \
                 alone",
            ),
            (_, Instrument::Whole) => Narrowing::NotApplicable,
        }
    }

    fn xml(&self, pad: usize) -> String {
        let p = " ".repeat(pad);
        match self {
            Narrowing::NotApplicable => format!(
                "{p}<pm:narrowsWhen><pm:absent><pm:reason>notApplicable</pm:reason>\
                 <pm:note>there is no range here to tighten</pm:note></pm:absent>\
                 </pm:narrowsWhen>\n"
            ),
            Narrowing::Instrument(condition) => format!(
                "{p}<pm:narrowsWhen>\n{p}  <pm:narrowing>\n{p}    \
                 <pm:condition>{condition}</pm:condition>\n{p}    \
                 <pm:kind>instrument</pm:kind>\n{p}  </pm:narrowing>\n{p}</pm:narrowsWhen>\n"
            ),
        }
    }
}

/// Who owns the edge of a claim.
///
/// ⛔⛔ THERE IS NO `none` VARIANT AND THAT IS THE POINT. `bound_fell_with_no_range` fired on the
/// first generated corpus, three filings out of six, and it is right: `none` says the bound is
/// where the MEASUREMENTS FELL, which describes a spread a point claim does not have. The honest
/// answer for an exact observation is `notApplicable`, and the schema names it one entry below.
/// Removing the variant is what stops the generator from being able to make the mistake again.
enum BoundOrigin<'a> {
    Intrinsic,
    Policy,
    NotApplicable(&'a str),
    Derived(&'a str),
}

impl BoundOrigin<'_> {
    fn xml(&self, pad: usize) -> String {
        let p = " ".repeat(pad);
        let absent = |reason: &str, note: &str| {
            format!(
                "{p}<pm:boundOrigin><pm:absent><pm:reason>{reason}</pm:reason>\
                 <pm:note>{note}</pm:note></pm:absent></pm:boundOrigin>\n"
            )
        };
        match self {
            BoundOrigin::Intrinsic => {
                format!("{p}<pm:boundOrigin><pm:origin>intrinsic</pm:origin></pm:boundOrigin>\n")
            }
            BoundOrigin::Policy => {
                format!("{p}<pm:boundOrigin><pm:origin>policy</pm:origin></pm:boundOrigin>\n")
            }
            BoundOrigin::NotApplicable(note) => absent("notApplicable", note),
            BoundOrigin::Derived(note) => absent("derived", note),
        }
    }
}

/// One `pm:StatedClaim`, or the typed absence where the instrument had nothing.
fn claim(
    b: Bounded,
    narrows: Narrowing,
    origin: BoundOrigin<'_>,
    as_of: &str,
    pad: usize,
    absent_note: &str,
) -> String {
    let p = " ".repeat(pad);
    let (low, high) = match b {
        Bounded::Range { low, high } => (low, high),
        Bounded::Unmeasured => {
            return format!(
                "{p}<pm:absent>\n{p}  <pm:reason>unmeasured</pm:reason>\n{p}  \
                 <pm:note>{absent_note}</pm:note>\n{p}</pm:absent>\n"
            );
        }
    };
    let ml = (low + high) / 2.0;
    let mut x = String::new();
    x.push_str(&format!("{p}<pm:claim>\n"));
    x.push_str(&format!(
        "{p}  <pm:low>{low:.4}</pm:low><pm:mostLikely>{ml:.4}</pm:mostLikely>\
         <pm:high>{high:.4}</pm:high>\n"
    ));
    x.push_str(&format!("{p}  <pm:unit>{UNIT}</pm:unit>\n"));
    x.push_str(&format!(
        "{p}  <pm:denominator><pm:period>{PERIOD}</pm:period></pm:denominator>\n"
    ));
    x.push_str(&narrows.xml(pad + 2));
    x.push_str(&origin.xml(pad + 2));
    x.push_str(&format!(
        "{p}  <pm:provenance><pm:party>bench</pm:party>\n{p}    \
         <pm:standing><pm:term><pm:taxonomy>urn:example:assertion-standing:2026</pm:taxonomy>\
         <pm:value>generated</pm:value></pm:term></pm:standing>\n{p}  </pm:provenance>\n"
    ));
    x.push_str(&format!("{p}  <pm:asOf>{as_of}</pm:asOf>\n"));
    x.push_str(&format!("{p}</pm:claim>\n"));
    x
}

/// ⭐⭐⭐ NOT ONE FILING IN THE CORPUS STATES A PATIENCE. Every one of them declines it, and a
/// bench knows it by construction because it is a parameter of the run. This is the field the
/// generator is most obviously worth having.
fn patience(s: &Settings, instrument: Instrument, as_of: &str) -> String {
    if instrument == Instrument::StockAndFlow {
        // ⛔ Q-3 IN THE FILING. A resource that waits for ever has no patience to record, so
        //   this is not a measurement anybody omitted, it is a concept the instrument lacks.
        return "          <pm:absent>\n            <pm:reason>unmeasured</pm:reason>\n            \
<pm:note>nothing in a stock-and-flow log gives a queued demand a \
                lifetime, so how long one survives being unanswered is not recorded</pm:note>\n          \
</pm:absent>\n"
            .to_string();
    }
    // ⛔⛔⛔ ZERO PATIENCE IS A CLAIM OF ZERO AND NOT AN ABSENCE, WHICH THE XSD SETTLED THE
    //    FIRST TIME THIS TRIED TO FILE IT THE OTHER WAY. `Demand/patience` is a `StatedClaim`,
    //    so its absence is a `ClaimAbsence` and `ClaimAbsenceReason` has no `none`. That is
    //    right: somebody measured how long this demand survives being held and the answer was
    //    nothing, which is a measurement rather than a missing column.
    //
    // ⚠️ `assets/sqlc/layers/patience.sqlc` says the opposite in a paragraph marked ⛔, and no
    //    filing anywhere exercises it. Reported rather than edited from here.
    // ⛔ A PATIENCE IS A SPAN OF TIME AND NOT THE LAYER'S UNIT, which is what separates it from
    //   `timeSlack`. It bounds no shares, so `slack_unit_mismatch` does not reach it.
    let secs = s.patience.as_secs_f64();
    format!(
        "          <pm:claim>\n            <pm:low>{secs:.1}</pm:low>\
         <pm:mostLikely>{secs:.1}</pm:mostLikely><pm:high>{secs:.1}</pm:high>\n            \
<pm:unit>seconds</pm:unit>\n            \
<pm:denominator><pm:absent><pm:reason>notApplicable</pm:reason>\
         </pm:absent></pm:denominator>\n            \
<pm:narrowsWhen><pm:absent><pm:reason>notApplicable</pm:reason>\
         <pm:note>there is no range here to tighten</pm:note></pm:absent></pm:narrowsWhen>\n            \
<pm:boundOrigin><pm:origin>policy</pm:origin></pm:boundOrigin>\n            \
<pm:asOf>{as_of}</pm:asOf>\n          </pm:claim>\n"
    )
}

/// The time buffer, in the layer's unit rather than in seconds.
///
/// ⛔ THE BRIDGE IS `quantity = duration x rate` AND IT IS INVISIBLE ONCE DONE, so it is said in
/// the note. `slack_unit_mismatch` requires a slack in the unit of the shares it bounds, and a
/// slack that skips the multiplication and keeps the right unit is caught by nothing.
fn time_slack(run: &Run, r: &Reading, instrument: Instrument, as_of: &str) -> String {
    let s = &run.settings;
    if instrument == Instrument::StockAndFlow {
        return "        <pm:absent>\n          <pm:reason>unmeasured</pm:reason>\n          \
<pm:note>no wait is recorded against a demand, because no demand is \
                recorded until it succeeds</pm:note>\n        </pm:absent>\n"
            .to_string();
    }
    let Some(demand) = mode(r.demand) else {
        return "        <pm:absent>\n          <pm:reason>unmeasured</pm:reason>\n          \
<pm:note>the rate the wait would be multiplied by is not \
                measured</pm:note>\n        </pm:absent>\n"
            .to_string();
    };
    let rate = demand / run.window.as_secs_f64();
    let quantity = s.patience.as_secs_f64() * rate;
    let mut x = String::new();
    x.push_str("        <pm:claim>\n");
    x.push_str(&format!(
        "          <pm:low>{quantity:.4}</pm:low><pm:mostLikely>{quantity:.4}</pm:mostLikely>\
         <pm:high>{quantity:.4}</pm:high>\n"
    ));
    x.push_str(&format!("          <pm:unit>{UNIT}</pm:unit>\n"));
    x.push_str(&format!(
        "          <pm:denominator><pm:period>{PERIOD}</pm:period></pm:denominator>\n"
    ));
    x.push_str(&Narrowing::NotApplicable.xml(10));
    x.push_str("          <pm:boundOrigin><pm:origin>policy</pm:origin></pm:boundOrigin>\n");
    x.push_str(&format!(
        "          <pm:provenance><pm:party>bench</pm:party>\n            \
         <pm:standing><pm:term><pm:taxonomy>urn:example:assertion-standing:2026</pm:taxonomy>\
         <pm:value>generated</pm:value></pm:term></pm:standing>\n            \
         <pm:note>a patience of {p:.0} seconds at a demand rate of {rate:.4} {UNIT} per second \
         is {quantity:.2} {UNIT}. The multiplication is the bridge from the duration that was \
         measured to the quantity the field takes</pm:note>\n          </pm:provenance>\n",
        p = s.patience.as_secs_f64()
    ));
    x.push_str(&format!("          <pm:asOf>{as_of}</pm:asOf>\n        </pm:claim>\n"));
    x
}

/// The quantum, and the part of the period the line is live for.
fn divisibility(run: &Run, as_of: &str) -> String {
    let s = &run.settings;
    let mut x = String::new();
    x.push_str("          <pm:divisibility>\n            <pm:divisibility>\n");
    x.push_str("              <pm:lumpy>\n                <pm:size>\n");
    // ⛔ THE QUANTUM IS IN THE UNIT OF THE NAMEPLATE IT DIVIDES, and this nameplate is a rate.
    //   `demand / q` and `nameplate / q` have to be COUNTS.
    x.push_str(&indent(
        &claim(
            Bounded::point(s.lot),
            Narrowing::NotApplicable,
            BoundOrigin::Derived("`LumpyQuantum/origin` says who sets the size of one unit, in \
                                  this same element"),
            as_of,
            0,
            "",
        ),
        18,
    ));
    x.push_str("                </pm:size>\n");
    x.push_str("                <pm:origin>intrinsic</pm:origin>\n              </pm:lumpy>\n");
    // ⭐ THE ON-DURATION, NOT THE GAP. The line runs the whole shift without stopping, so the
    //   duty fraction is one and the window is the period.
    let hours = run.window.as_secs_f64() / 3600.0;
    x.push_str(&format!(
        "              <pm:window>\n                <pm:quantum>\n                  \
         <pm:size>\n                    <pm:claim>\n                      \
         <pm:low>{hours:.1}</pm:low><pm:mostLikely>{hours:.1}</pm:mostLikely>\
         <pm:high>{hours:.1}</pm:high>\n                      \
         <pm:unit>hours</pm:unit>\n                      \
         <pm:denominator><pm:period>{PERIOD}</pm:period></pm:denominator>\n                      \
         <pm:narrowsWhen><pm:absent><pm:reason>notApplicable</pm:reason>\
         <pm:note>there is no range here to tighten</pm:note></pm:absent></pm:narrowsWhen>\n                      \
<pm:boundOrigin><pm:origin>intrinsic</pm:origin>\
         </pm:boundOrigin>\n                      <pm:asOf>{as_of}</pm:asOf>\n                    \
         </pm:claim>\n                  </pm:size>\n                  \
         <pm:origin>intrinsic</pm:origin>\n                </pm:quantum>\n              \
         </pm:window>\n"
    ));
    x.push_str("            </pm:divisibility>\n          </pm:divisibility>\n");
    x
}

fn indent(block: &str, pad: usize) -> String {
    let p = " ".repeat(pad);
    block
        .lines()
        .map(|l| if l.is_empty() { l.to_string() } else { format!("{p}{l}") })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}
