//! What a supply with more than one lot size can and cannot fill exactly.
//!
//! ⭐⭐⭐ THE SCHEMA STATES A CONGRUENCE AND THIS IS THE GENERALISATION THAT BREAKS IT.
//! `pm:Remainder`'s annotation says, of a lumpy supply whose nameplate is a whole multiple of the
//! quantum, that `r ≡ -demand (mod q)` **always**. That is exactly right for ONE quantum. A supply
//! with two lot sizes has no single `q`: the demands it can meet with no remainder at all are the
//! **numerical semigroup** generated by both, and the congruence has nothing to say about them.
//!
//! ⛔⛔ AND THE TWO LAWS DISAGREE QUALITATIVELY, NOT BY A CONSTANT. A congruence says the residue
//! is there for ever, cycling with period `q`. A semigroup says the residue **stops**: above the
//! Frobenius number every demand is fillable exactly and the remainder is identically zero. One
//! law predicts a permanent irreducible cost and the other predicts it vanishes at a computable
//! threshold, and they are describing the same shop.
//!
//! ⭐ Sylvester, for coprime `a` and `b`: the largest unfillable demand is `ab - a - b`, and the
//! count of unfillable demands is `(a-1)(b-1)/2`. Both are checked against a sieve below rather
//! than trusted, because a formula quoted from a search is one witness asserting.

/// The set of demands a supply with these lot sizes can fill with nothing left over.
pub struct Fillable {
    pub generators: Vec<u64>,
    /// `in_semigroup[s]` is true where a demand of exactly `s` can be met by whole lots.
    in_semigroup: Vec<bool>,
}

impl Fillable {
    /// Sieves the semigroup up to `ceiling`, which must be comfortably past the Frobenius number.
    pub fn new(generators: Vec<u64>, ceiling: usize) -> Self {
        let mut reachable = vec![false; ceiling + 1];
        reachable[0] = true;
        for value in 1..=ceiling {
            for g in &generators {
                let g = *g as usize;
                if g <= value && reachable[value - g] {
                    reachable[value] = true;
                    break;
                }
            }
        }
        Fillable {
            generators,
            in_semigroup: reachable,
        }
    }

    pub fn fills_exactly(&self, demand: u64) -> bool {
        self.in_semigroup
            .get(demand as usize)
            .copied()
            .unwrap_or(true)
    }

    /// Every demand below the ceiling that no combination of lots can meet exactly.
    pub fn gaps(&self) -> Vec<u64> {
        (1..self.in_semigroup.len())
            .filter(|s| !self.in_semigroup[*s])
            .map(|s| s as u64)
            .collect()
    }

    /// The largest demand that cannot be met exactly. `None` where a lot size is 1.
    pub fn frobenius(&self) -> Option<u64> {
        self.gaps().last().copied()
    }

    /// ⭐ THE SMALLEST OVERSHOOT. A shop that will not leave a customer short ships the next
    /// fillable amount up, and the difference is supply nobody asked for. It is zero exactly on
    /// the semigroup, which is what makes the gap set the thing to look at.
    pub fn overshoot(&self, demand: u64) -> u64 {
        let mut up = demand;
        while !self.fills_exactly(up) {
            up += 1;
        }
        up - demand
    }

    /// Sylvester's closed form, for the two-generator case only.
    pub fn sylvester(&self) -> Option<(u64, u64)> {
        if self.generators.len() != 2 {
            return None;
        }
        let (a, b) = (self.generators[0], self.generators[1]);
        if gcd(a, b) != 1 {
            return None;
        }
        Some((a * b - a - b, (a - 1) * (b - 1) / 2))
    }
}

pub fn gcd(a: u64, b: u64) -> u64 {
    if b == 0 { a } else { gcd(b, a % b) }
}
