-- §2  The compositions: every splice site, and the template it lands in.
-- rank/compose_edges.sqlc, the edge list as it stands.
WITH rank_compose_edges AS (
-- public.compose_edge, generated by examples/compositions/main.rs from assets/sqlc/.
SELECT e.parent, e.child, e.splices, e.inner_joins
FROM public.compose_edge e
)
SELECT e.parent AS "parent!", e.child AS "child!", e.splices::bigint AS "splices!"
FROM (
    SELECT * FROM rank_compose_edges
) e
ORDER BY e.parent, e.child
