-- the fit axis each rule on checks/roster.sqlc reads, declared.
SELECT * FROM (VALUES
  ('fit_disagrees',                        'filed against derived'::public.fit_axis),
  ('shares_do_not_sum',                    'derived fit'),
  ('stated_quantity_is_not_the_magnitude', 'derived fit'),
  ('nobody_named_as_unserved',             'derived fit'),
  ('exposure_unaccounted',                 'derived fit'),
  ('share_exceeds_slack',                  'filed sign'),
  ('slack_unit_mismatch',                  'not read'),
  ('quantum_unit_mismatch',                'not read'),
  ('nameplate_not_a_multiple',             'not read'),
  ('draw_exceeds_the_supply',              'not read'),
  ('clearance_with_unserved',              'filed sign'),
  ('unresolved_part',                      'not read'),
  ('jagged_layer',                         'not read'),
  ('layers_move_together',                 'not read'),
  ('coupling_does_not_attenuate',          'not read'),
  ('narrows_a_point_value',                'not read'),
  ('range_says_no_range',                  'not read'),
  ('bound_fell_with_no_range',             'not read'),
  ('identity_does_not_compute_the_claim',  'not read'),
  ('window_lost_or_summed',                'not read'),
  ('derived_slack_over_a_window',          'not read'),
  ('window_not_applicable_on_a_rate',      'not read'),
  ('window_size_not_applicable',           'not read'),
  ('elimination_not_applicable_with_parts','not read'),
  ('fusion_sum_disagrees',                 'not read'),
  ('local_part_dangles',                   'not read'),
  ('unit_crossing_without_a_factor',       'not read'),
  ('regime_crossing_without_a_citation',   'not read'),
  ('part_regime_disagrees',                'not read'),
  ('conversion_cycle_does_not_close',      'not read'),
  ('one_part_fusion_alters_its_part',      'not read'),
  ('denied_remainder_is_not_contradicted', 'not read')
) AS a(slug, axis)
